/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables;


import com.kalaazu.persistence.database.entities.Indexes;
import com.kalaazu.persistence.database.entities.Kalaazu;
import com.kalaazu.persistence.database.entities.Keys;
import com.kalaazu.persistence.database.entities.tables.records.ClansBattlestationsItemsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Items equipped in the CBS.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansBattlestationsItems extends TableImpl<ClansBattlestationsItemsRecord> {

    private static final long serialVersionUID = 576665217;

    /**
     * The reference instance of <code>kalaazu.clans_battlestations_items</code>
     */
    public static final ClansBattlestationsItems CLANS_BATTLESTATIONS_ITEMS = new ClansBattlestationsItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClansBattlestationsItemsRecord> getRecordType() {
        return ClansBattlestationsItemsRecord.class;
    }

    /**
     * The column <code>kalaazu.clans_battlestations_items.id</code>. Primary Key.
     */
    public final TableField<ClansBattlestationsItemsRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary Key.");

    /**
     * The column <code>kalaazu.clans_battlestations_items.clans_battlestations_id</code>. CBS where item is equipped.
     */
    public final TableField<ClansBattlestationsItemsRecord, Byte> CLANS_BATTLESTATIONS_ID = createField(DSL.name("clans_battlestations_id"), org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "CBS where item is equipped.");

    /**
     * The column <code>kalaazu.clans_battlestations_items.accounts_items_id</code>. Equipped item.
     */
    public final TableField<ClansBattlestationsItemsRecord, Integer> ACCOUNTS_ITEMS_ID = createField(DSL.name("accounts_items_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Equipped item.");

    /**
     * The column <code>kalaazu.clans_battlestations_items.slot</code>. Position where the item is equipped (A = 9, B = 10).
     */
    public final TableField<ClansBattlestationsItemsRecord, Byte> SLOT = createField(DSL.name("slot"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.TINYINT)), this, "Position where the item is equipped (A = 9, B = 10).");

    /**
     * The column <code>kalaazu.clans_battlestations_items.date</code>. Date when the item was equipped.
     */
    public final TableField<ClansBattlestationsItemsRecord, Timestamp> DATE = createField(DSL.name("date"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "Date when the item was equipped.");

    /**
     * Create a <code>kalaazu.clans_battlestations_items</code> table reference
     */
    public ClansBattlestationsItems() {
        this(DSL.name("clans_battlestations_items"), null);
    }

    /**
     * Create an aliased <code>kalaazu.clans_battlestations_items</code> table reference
     */
    public ClansBattlestationsItems(String alias) {
        this(DSL.name(alias), CLANS_BATTLESTATIONS_ITEMS);
    }

    /**
     * Create an aliased <code>kalaazu.clans_battlestations_items</code> table reference
     */
    public ClansBattlestationsItems(Name alias) {
        this(alias, CLANS_BATTLESTATIONS_ITEMS);
    }

    private ClansBattlestationsItems(Name alias, Table<ClansBattlestationsItemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClansBattlestationsItems(Name alias, Table<ClansBattlestationsItemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Items equipped in the CBS."));
    }

    public <O extends Record> ClansBattlestationsItems(Table<O> child, ForeignKey<O, ClansBattlestationsItemsRecord> key) {
        super(child, key, CLANS_BATTLESTATIONS_ITEMS);
    }

    @Override
    public Schema getSchema() {
        return Kalaazu.KALAAZU;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLANS_BATTLESTATIONS_ITEMS_CLANS_BATTLESTATIONS_ITEMS_ACCOUNTS_ITEMS_ID_IDX, Indexes.CLANS_BATTLESTATIONS_ITEMS_CLANS_BATTLESTATIONS_ITEMS_CLANS_BATTLESTATIONS_ID_IDX, Indexes.CLANS_BATTLESTATIONS_ITEMS_PRIMARY);
    }

    @Override
    public Identity<ClansBattlestationsItemsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CLANS_BATTLESTATIONS_ITEMS;
    }

    @Override
    public UniqueKey<ClansBattlestationsItemsRecord> getPrimaryKey() {
        return Keys.KEY_CLANS_BATTLESTATIONS_ITEMS_PRIMARY;
    }

    @Override
    public List<UniqueKey<ClansBattlestationsItemsRecord>> getKeys() {
        return Arrays.<UniqueKey<ClansBattlestationsItemsRecord>>asList(Keys.KEY_CLANS_BATTLESTATIONS_ITEMS_PRIMARY);
    }

    @Override
    public List<ForeignKey<ClansBattlestationsItemsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClansBattlestationsItemsRecord, ?>>asList(Keys.CLANS_BATTLESTATIONS_ITEMS_CLANS_BATTLESTATIONS, Keys.CLANS_BATTLESTATIONS_ITEMS_ACCOUNTS_ITEMS);
    }

    public ClansBattlestations clansBattlestations() {
        return new ClansBattlestations(this, Keys.CLANS_BATTLESTATIONS_ITEMS_CLANS_BATTLESTATIONS);
    }

    public AccountsItems accountsItems() {
        return new AccountsItems(this, Keys.CLANS_BATTLESTATIONS_ITEMS_ACCOUNTS_ITEMS);
    }

    @Override
    public ClansBattlestationsItems as(String alias) {
        return new ClansBattlestationsItems(DSL.name(alias), this);
    }

    @Override
    public ClansBattlestationsItems as(Name alias) {
        return new ClansBattlestationsItems(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClansBattlestationsItems rename(String name) {
        return new ClansBattlestationsItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClansBattlestationsItems rename(Name name) {
        return new ClansBattlestationsItems(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Byte, Integer, Byte, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
