/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables;


import com.kalaazu.persistence.database.entities.Indexes;
import com.kalaazu.persistence.database.entities.Kalaazu;
import com.kalaazu.persistence.database.entities.Keys;
import com.kalaazu.persistence.database.entities.tables.records.GalaxygatesSpawnsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Stage spawn for each stage.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GalaxygatesSpawns extends TableImpl<GalaxygatesSpawnsRecord> {

    private static final long serialVersionUID = 915699993;

    /**
     * The reference instance of <code>kalaazu.galaxygates_spawns</code>
     */
    public static final GalaxygatesSpawns GALAXYGATES_SPAWNS = new GalaxygatesSpawns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GalaxygatesSpawnsRecord> getRecordType() {
        return GalaxygatesSpawnsRecord.class;
    }

    /**
     * The column <code>kalaazu.galaxygates_spawns.id</code>. Primary Key.
     */
    public final TableField<GalaxygatesSpawnsRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary Key.");

    /**
     * The column <code>kalaazu.galaxygates_spawns.npcs_id</code>. NPC to spawn.
     */
    public final TableField<GalaxygatesSpawnsRecord, Byte> NPCS_ID = createField(DSL.name("npcs_id"), org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "NPC to spawn.");

    /**
     * The column <code>kalaazu.galaxygates_spawns.amount</code>. Amount of NPCs to spawn.
     */
    public final TableField<GalaxygatesSpawnsRecord, Byte> AMOUNT = createField(DSL.name("amount"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("20", org.jooq.impl.SQLDataType.TINYINT)), this, "Amount of NPCs to spawn.");

    /**
     * Create a <code>kalaazu.galaxygates_spawns</code> table reference
     */
    public GalaxygatesSpawns() {
        this(DSL.name("galaxygates_spawns"), null);
    }

    /**
     * Create an aliased <code>kalaazu.galaxygates_spawns</code> table reference
     */
    public GalaxygatesSpawns(String alias) {
        this(DSL.name(alias), GALAXYGATES_SPAWNS);
    }

    /**
     * Create an aliased <code>kalaazu.galaxygates_spawns</code> table reference
     */
    public GalaxygatesSpawns(Name alias) {
        this(alias, GALAXYGATES_SPAWNS);
    }

    private GalaxygatesSpawns(Name alias, Table<GalaxygatesSpawnsRecord> aliased) {
        this(alias, aliased, null);
    }

    private GalaxygatesSpawns(Name alias, Table<GalaxygatesSpawnsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Stage spawn for each stage."));
    }

    public <O extends Record> GalaxygatesSpawns(Table<O> child, ForeignKey<O, GalaxygatesSpawnsRecord> key) {
        super(child, key, GALAXYGATES_SPAWNS);
    }

    @Override
    public Schema getSchema() {
        return Kalaazu.KALAAZU;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GALAXYGATES_SPAWNS_GALAXYGATES_SPAWNS_NPCS_ID_IDX, Indexes.GALAXYGATES_SPAWNS_PRIMARY);
    }

    @Override
    public Identity<GalaxygatesSpawnsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GALAXYGATES_SPAWNS;
    }

    @Override
    public UniqueKey<GalaxygatesSpawnsRecord> getPrimaryKey() {
        return Keys.KEY_GALAXYGATES_SPAWNS_PRIMARY;
    }

    @Override
    public List<UniqueKey<GalaxygatesSpawnsRecord>> getKeys() {
        return Arrays.<UniqueKey<GalaxygatesSpawnsRecord>>asList(Keys.KEY_GALAXYGATES_SPAWNS_PRIMARY);
    }

    @Override
    public List<ForeignKey<GalaxygatesSpawnsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GalaxygatesSpawnsRecord, ?>>asList(Keys.GALAXYGATES_SPAWNS_NPCS);
    }

    public Npcs npcs() {
        return new Npcs(this, Keys.GALAXYGATES_SPAWNS_NPCS);
    }

    @Override
    public GalaxygatesSpawns as(String alias) {
        return new GalaxygatesSpawns(DSL.name(alias), this);
    }

    @Override
    public GalaxygatesSpawns as(Name alias) {
        return new GalaxygatesSpawns(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GalaxygatesSpawns rename(String name) {
        return new GalaxygatesSpawns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GalaxygatesSpawns rename(Name name) {
        return new GalaxygatesSpawns(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Byte, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
