spring:
  datasource:
    password: ${MYSQL_PASSWORD}
    url: jdbc:mariadb://localhost:3306/kalaazu
    username: ${MYSQL_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  game:
    printPackets: true
  port:
    server: 8080
    policy: 843
    chat: 8082

server:
  port: 8081
