spring:
  threads:
    virtual:
      enabled: true

  task:
    scheduling:
      pool:
        size: 8

  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:kalaazu}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

app:
  game:
    packets:
      printOut: true
      printIn: true

  port:
    server: ${GAME_SERVER_PORT:8080}
    policy: ${POLICY_SERVER_PORT:843}
    chat: ${CHAT_SERVER_PORT:8082}

server:
  port: ${WEB_SERVER_PORT:8081}
