/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.records;


import com.kalaazu.persistence.database.tables.AccountsShips;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Ships bough by an account.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AccountsShipsRecord extends UpdatableRecordImpl<AccountsShipsRecord> implements Record8<Integer, Integer, Byte, Byte, Long, Integer, Integer, Byte> {

    private static final long serialVersionUID = 915777172;

    /**
     * Create a detached AccountsShipsRecord
     */
    public AccountsShipsRecord() {
        super(AccountsShips.ACCOUNTS_SHIPS);
    }

    /**
     * Create a detached, initialised AccountsShipsRecord
     */
    public AccountsShipsRecord(
            Integer id, Integer accountsId, Byte shipsId, Byte mapsId, Long position, Integer health, Integer nanohull,
            Byte gfx
    ) {
        super(AccountsShips.ACCOUNTS_SHIPS);

        set(0, id);
        set(1, accountsId);
        set(2, shipsId);
        set(3, mapsId);
        set(4, position);
        set(5, health);
        set(6, nanohull);
        set(7, gfx);
    }

    /**
     * Getter for <code>kalaazu.accounts_ships.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.accounts_ships.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_ships.accounts_id</code>.
     */
    public Integer getAccountsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.accounts_ships.accounts_id</code>.
     */
    public void setAccountsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_ships.ships_id</code>.
     */
    public Byte getShipsId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.accounts_ships.ships_id</code>.
     */
    public void setShipsId(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_ships.maps_id</code>.
     */
    public Byte getMapsId() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kalaazu.accounts_ships.maps_id</code>.
     */
    public void setMapsId(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_ships.position</code>. Position on map.
     */
    public Long getPosition() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>kalaazu.accounts_ships.position</code>. Position on map.
     */
    public void setPosition(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_ships.health</code>. Health points.
     */
    public Integer getHealth() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kalaazu.accounts_ships.health</code>. Health points.
     */
    public void setHealth(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_ships.nanohull</code>. Nanohull points.
     */
    public Integer getNanohull() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kalaazu.accounts_ships.nanohull</code>. Nanohull points.
     */
    public void setNanohull(Integer value) {
        set(6, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.accounts_ships.gfx</code>. Ship graphic (for WIZ-X).
     */
    public Byte getGfx() {
        return (Byte) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.accounts_ships.gfx</code>. Ship graphic (for WIZ-X).
     */
    public void setGfx(Byte value) {
        set(7, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row8<Integer, Integer, Byte, Byte, Long, Integer, Integer, Byte> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Byte, Byte, Long, Integer, Integer, Byte> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AccountsShips.ACCOUNTS_SHIPS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AccountsShips.ACCOUNTS_SHIPS.ACCOUNTS_ID;
    }

    @Override
    public Field<Byte> field3() {
        return AccountsShips.ACCOUNTS_SHIPS.SHIPS_ID;
    }

    @Override
    public Field<Byte> field4() {
        return AccountsShips.ACCOUNTS_SHIPS.MAPS_ID;
    }

    @Override
    public Field<Long> field5() {
        return AccountsShips.ACCOUNTS_SHIPS.POSITION;
    }

    @Override
    public Field<Integer> field6() {
        return AccountsShips.ACCOUNTS_SHIPS.HEALTH;
    }

    @Override
    public Field<Integer> field7() {
        return AccountsShips.ACCOUNTS_SHIPS.NANOHULL;
    }

    @Override
    public Field<Byte> field8() {
        return AccountsShips.ACCOUNTS_SHIPS.GFX;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAccountsId();
    }

    @Override
    public Byte component3() {
        return getShipsId();
    }

    @Override
    public Byte component4() {
        return getMapsId();
    }

    @Override
    public Long component5() {
        return getPosition();
    }

    @Override
    public Integer component6() {
        return getHealth();
    }

    @Override
    public Integer component7() {
        return getNanohull();
    }

    @Override
    public Byte component8() {
        return getGfx();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAccountsId();
    }

    @Override
    public Byte value3() {
        return getShipsId();
    }

    @Override
    public Byte value4() {
        return getMapsId();
    }

    @Override
    public Long value5() {
        return getPosition();
    }

    @Override
    public Integer value6() {
        return getHealth();
    }

    @Override
    public Integer value7() {
        return getNanohull();
    }

    @Override
    public Byte value8() {
        return getGfx();
    }

    @Override
    public AccountsShipsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AccountsShipsRecord value2(Integer value) {
        setAccountsId(value);
        return this;
    }

    @Override
    public AccountsShipsRecord value3(Byte value) {
        setShipsId(value);
        return this;
    }

    @Override
    public AccountsShipsRecord value4(Byte value) {
        setMapsId(value);
        return this;
    }

    @Override
    public AccountsShipsRecord value5(Long value) {
        setPosition(value);
        return this;
    }

    @Override
    public AccountsShipsRecord value6(Integer value) {
        setHealth(value);
        return this;
    }

    @Override
    public AccountsShipsRecord value7(Integer value) {
        setNanohull(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AccountsShipsRecord value8(Byte value) {
        setGfx(value);
        return this;
    }

    @Override
    public AccountsShipsRecord values(
            Integer value1, Integer value2, Byte value3, Byte value4, Long value5, Integer value6, Integer value7,
            Byte value8
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }
}
