/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.records;


import com.kalaazu.persistence.database.tables.ClansDiplomacies;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.sql.Timestamp;


/**
 * Diplomacy table for clans.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ClansDiplomaciesRecord extends UpdatableRecordImpl<ClansDiplomaciesRecord> implements Record7<Integer, Integer, Integer, Timestamp, Timestamp, Byte, Byte> {

    private static final long serialVersionUID = -51666599;

    /**
     * Create a detached ClansDiplomaciesRecord
     */
    public ClansDiplomaciesRecord() {
        super(ClansDiplomacies.CLANS_DIPLOMACIES);
    }

    /**
     * Create a detached, initialised ClansDiplomaciesRecord
     */
    public ClansDiplomaciesRecord(
            Integer id, Integer fromClansId, Integer toClansId, Timestamp date, Timestamp expires, Byte status,
            Byte type
    ) {
        super(ClansDiplomacies.CLANS_DIPLOMACIES);

        set(0, id);
        set(1, fromClansId);
        set(2, toClansId);
        set(3, date);
        set(4, expires);
        set(5, status);
        set(6, type);
    }

    /**
     * Getter for <code>kalaazu.clans_diplomacies.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.clans_diplomacies.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.clans_diplomacies.from_clans_id</code>. Clan that made the request.
     */
    public Integer getFromClansId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.clans_diplomacies.from_clans_id</code>. Clan that made the request.
     */
    public void setFromClansId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.clans_diplomacies.to_clans_id</code>. Clan that receives the request.
     */
    public Integer getToClansId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kalaazu.clans_diplomacies.to_clans_id</code>. Clan that receives the request.
     */
    public void setToClansId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.clans_diplomacies.date</code>. Diplomacy creation date.
     */
    public Timestamp getDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>kalaazu.clans_diplomacies.date</code>. Diplomacy creation date.
     */
    public void setDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.clans_diplomacies.expires</code>. Date when the diplomacy expires.
     */
    public Timestamp getExpires() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>kalaazu.clans_diplomacies.expires</code>. Date when the diplomacy expires.
     */
    public void setExpires(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.clans_diplomacies.status</code>. Status of the diplomacy. 0 = not accepted, 1 = accepted, 2 = rejected, 3 = over.
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>kalaazu.clans_diplomacies.status</code>. Status of the diplomacy. 0 = not accepted, 1 = accepted, 2 = rejected, 3 = over.
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.clans_diplomacies.type</code>. Diplomacy type. 1 = War, 2 = NAP, 3 = Alliance.
     */
    public Byte getType() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.clans_diplomacies.type</code>. Diplomacy type. 1 = War, 2 = NAP, 3 = Alliance.
     */
    public void setType(Byte value) {
        set(6, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row7<Integer, Integer, Integer, Timestamp, Timestamp, Byte, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, Timestamp, Timestamp, Byte, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ClansDiplomacies.CLANS_DIPLOMACIES.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ClansDiplomacies.CLANS_DIPLOMACIES.FROM_CLANS_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ClansDiplomacies.CLANS_DIPLOMACIES.TO_CLANS_ID;
    }

    @Override
    public Field<Timestamp> field4() {
        return ClansDiplomacies.CLANS_DIPLOMACIES.DATE;
    }

    @Override
    public Field<Timestamp> field5() {
        return ClansDiplomacies.CLANS_DIPLOMACIES.EXPIRES;
    }

    @Override
    public Field<Byte> field6() {
        return ClansDiplomacies.CLANS_DIPLOMACIES.STATUS;
    }

    @Override
    public Field<Byte> field7() {
        return ClansDiplomacies.CLANS_DIPLOMACIES.TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getFromClansId();
    }

    @Override
    public Integer component3() {
        return getToClansId();
    }

    @Override
    public Timestamp component4() {
        return getDate();
    }

    @Override
    public Timestamp component5() {
        return getExpires();
    }

    @Override
    public Byte component6() {
        return getStatus();
    }

    @Override
    public Byte component7() {
        return getType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getFromClansId();
    }

    @Override
    public Integer value3() {
        return getToClansId();
    }

    @Override
    public Timestamp value4() {
        return getDate();
    }

    @Override
    public Timestamp value5() {
        return getExpires();
    }

    @Override
    public Byte value6() {
        return getStatus();
    }

    @Override
    public Byte value7() {
        return getType();
    }

    @Override
    public ClansDiplomaciesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClansDiplomaciesRecord value2(Integer value) {
        setFromClansId(value);
        return this;
    }

    @Override
    public ClansDiplomaciesRecord value3(Integer value) {
        setToClansId(value);
        return this;
    }

    @Override
    public ClansDiplomaciesRecord value4(Timestamp value) {
        setDate(value);
        return this;
    }

    @Override
    public ClansDiplomaciesRecord value5(Timestamp value) {
        setExpires(value);
        return this;
    }

    @Override
    public ClansDiplomaciesRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public ClansDiplomaciesRecord value7(Byte value) {
        setType(value);
        return this;
    }

    @Override
    public ClansDiplomaciesRecord values(
            Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5, Byte value6, Byte value7
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
