/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.records;


import com.kalaazu.persistence.database.tables.Galaxygates;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Galaxy gates from the server.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GalaxygatesRecord extends UpdatableRecordImpl<GalaxygatesRecord> implements Record4<Byte, String, Byte, Byte> {

    private static final long serialVersionUID = -2110718784;

    /**
     * Create a detached GalaxygatesRecord
     */
    public GalaxygatesRecord() {
        super(Galaxygates.GALAXYGATES);
    }

    /**
     * Create a detached, initialised GalaxygatesRecord
     */
    public GalaxygatesRecord(Byte id, String name, Byte galaxygatesWavesId, Byte parts) {
        super(Galaxygates.GALAXYGATES);

        set(0, id);
        set(1, name);
        set(2, galaxygatesWavesId);
        set(3, parts);
    }

    /**
     * Getter for <code>kalaazu.galaxygates.id</code>. Primary Key.
     */
    public Byte getId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>kalaazu.galaxygates.id</code>. Primary Key.
     */
    public void setId(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.galaxygates.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kalaazu.galaxygates.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.galaxygates.galaxygates_waves_id</code>. Starting wave.
     */
    public Byte getGalaxygatesWavesId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.galaxygates.galaxygates_waves_id</code>. Starting wave.
     */
    public void setGalaxygatesWavesId(Byte value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.galaxygates.parts</code>. Necessary parts to build the gate.
     */
    public Byte getParts() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.galaxygates.parts</code>. Necessary parts to build the gate.
     */
    public void setParts(Byte value) {
        set(3, value);
    }

    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    @Override
    public Row4<Byte, String, Byte, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Byte, String, Byte, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Byte> field1() {
        return Galaxygates.GALAXYGATES.ID;
    }

    @Override
    public Field<String> field2() {
        return Galaxygates.GALAXYGATES.NAME;
    }

    @Override
    public Field<Byte> field3() {
        return Galaxygates.GALAXYGATES.GALAXYGATES_WAVES_ID;
    }

    @Override
    public Field<Byte> field4() {
        return Galaxygates.GALAXYGATES.PARTS;
    }

    @Override
    public Byte component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Byte component3() {
        return getGalaxygatesWavesId();
    }

    @Override
    public Byte component4() {
        return getParts();
    }

    @Override
    public Byte value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Byte value3() {
        return getGalaxygatesWavesId();
    }

    @Override
    public Byte value4() {
        return getParts();
    }

    @Override
    public GalaxygatesRecord value1(Byte value) {
        setId(value);
        return this;
    }

    @Override
    public GalaxygatesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GalaxygatesRecord value3(Byte value) {
        setGalaxygatesWavesId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public GalaxygatesRecord value4(Byte value) {
        setParts(value);
        return this;
    }

    @Override
    public GalaxygatesRecord values(Byte value1, String value2, Byte value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
