/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.records;


import com.kalaazu.persistence.database.tables.RewardsShips;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Many to many relations.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RewardsShipsRecord extends UpdatableRecordImpl<RewardsShipsRecord> implements Record3<Byte, Byte, Short> {

    private static final long serialVersionUID = 1672241233;

    /**
     * Create a detached RewardsShipsRecord
     */
    public RewardsShipsRecord() {
        super(RewardsShips.REWARDS_SHIPS);
    }

    /**
     * Create a detached, initialised RewardsShipsRecord
     */
    public RewardsShipsRecord(Byte id, Byte shipsId, Short rewardsId) {
        super(RewardsShips.REWARDS_SHIPS);

        set(0, id);
        set(1, shipsId);
        set(2, rewardsId);
    }

    /**
     * Getter for <code>kalaazu.rewards_ships.id</code>. Primary Key.
     */
    public Byte getId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>kalaazu.rewards_ships.id</code>. Primary Key.
     */
    public void setId(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.rewards_ships.ships_id</code>. Ship ID.
     */
    public Byte getShipsId() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>kalaazu.rewards_ships.ships_id</code>. Ship ID.
     */
    public void setShipsId(Byte value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.rewards_ships.rewards_id</code>. Reward to award.
     */
    public Short getRewardsId() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.rewards_ships.rewards_id</code>. Reward to award.
     */
    public void setRewardsId(Short value) {
        set(2, value);
    }

    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<Byte, Byte, Short> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Byte, Byte, Short> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Byte> field1() {
        return RewardsShips.REWARDS_SHIPS.ID;
    }

    @Override
    public Field<Byte> field2() {
        return RewardsShips.REWARDS_SHIPS.SHIPS_ID;
    }

    @Override
    public Field<Short> field3() {
        return RewardsShips.REWARDS_SHIPS.REWARDS_ID;
    }

    @Override
    public Byte component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getShipsId();
    }

    @Override
    public Short component3() {
        return getRewardsId();
    }

    @Override
    public Byte value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getShipsId();
    }

    @Override
    public Short value3() {
        return getRewardsId();
    }

    @Override
    public RewardsShipsRecord value1(Byte value) {
        setId(value);
        return this;
    }

    @Override
    public RewardsShipsRecord value2(Byte value) {
        setShipsId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public RewardsShipsRecord value3(Short value) {
        setRewardsId(value);
        return this;
    }

    @Override
    public RewardsShipsRecord values(Byte value1, Byte value2, Short value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
