/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.tables;


import com.kalaazu.persistence.database.Indexes;
import com.kalaazu.persistence.database.Kalaazu;
import com.kalaazu.persistence.database.Keys;
import com.kalaazu.persistence.database.records.ClansRankingRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Clan ranking.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ClansRanking extends TableImpl<ClansRankingRecord> {

    /**
     * The reference instance of <code>kalaazu.clans_ranking</code>
     */
    public static final ClansRanking CLANS_RANKING = new ClansRanking();
    private static final long serialVersionUID = 1835600099;
    /**
     * The column <code>kalaazu.clans_ranking.id</code>. Primary Key.
     */
    public final TableField<ClansRankingRecord, Integer> ID = createField(
            DSL.name("id"),
            org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true),
            this,
            "Primary Key."
    );
    /**
     * The column <code>kalaazu.clans_ranking.clans_id</code>. Clan ID.
     */
    public final TableField<ClansRankingRecord, Integer> CLANS_ID = createField(
            DSL.name("clans_id"),
            org.jooq.impl.SQLDataType.INTEGER.nullable(false),
            this,
            "Clan ID."
    );
    /**
     * The column <code>kalaazu.clans_ranking.points</code>. Points in the ranking.
     */
    public final TableField<ClansRankingRecord, Integer> POINTS = createField(
            DSL.name("points"),
            org.jooq.impl.SQLDataType.INTEGER.nullable(false)
                                             .defaultValue(org.jooq.impl.DSL.field(
                                                     "0",
                                                     org.jooq.impl.SQLDataType.INTEGER
                                             )),
            this,
            "Points in the ranking."
    );
    /**
     * The column <code>kalaazu.clans_ranking.best_points</code>. Biggest amount of rank points ever achieved.
     */
    public final TableField<ClansRankingRecord, Integer> BEST_POINTS = createField(
            DSL.name("best_points"),
            org.jooq.impl.SQLDataType.INTEGER.nullable(false)
                                             .defaultValue(org.jooq.impl.DSL.field(
                                                     "0",
                                                     org.jooq.impl.SQLDataType.INTEGER
                                             )),
            this,
            "Biggest amount of rank points ever achieved."
    );

    /**
     * Create a <code>kalaazu.clans_ranking</code> table reference
     */
    public ClansRanking() {
        this(DSL.name("clans_ranking"), null);
    }

    /**
     * Create an aliased <code>kalaazu.clans_ranking</code> table reference
     */
    public ClansRanking(String alias) {
        this(DSL.name(alias), CLANS_RANKING);
    }

    /**
     * Create an aliased <code>kalaazu.clans_ranking</code> table reference
     */
    public ClansRanking(Name alias) {
        this(alias, CLANS_RANKING);
    }

    private ClansRanking(Name alias, Table<ClansRankingRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClansRanking(Name alias, Table<ClansRankingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Clan ranking."));
    }

    public <O extends Record> ClansRanking(Table<O> child, ForeignKey<O, ClansRankingRecord> key) {
        super(child, key, CLANS_RANKING);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClansRankingRecord> getRecordType() {
        return ClansRankingRecord.class;
    }

    @Override
    public Schema getSchema() {
        return Kalaazu.KALAAZU;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLANS_RANKING_CLANS_RANKING_ACCOUNTS_ID_IDX, Indexes.CLANS_RANKING_PRIMARY);
    }

    @Override
    public Identity<ClansRankingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CLANS_RANKING;
    }

    @Override
    public UniqueKey<ClansRankingRecord> getPrimaryKey() {
        return Keys.KEY_CLANS_RANKING_PRIMARY;
    }

    @Override
    public List<UniqueKey<ClansRankingRecord>> getKeys() {
        return Arrays.<UniqueKey<ClansRankingRecord>>asList(
                Keys.KEY_CLANS_RANKING_PRIMARY,
                Keys.KEY_CLANS_RANKING_CLANS_RANKING_ACCOUNTS_ID_IDX
        );
    }

    @Override
    public List<ForeignKey<ClansRankingRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClansRankingRecord, ?>>asList(Keys.CLANS_RANKING_CLANS);
    }

    public Clans clans() {
        return new Clans(this, Keys.CLANS_RANKING_CLANS);
    }

    @Override
    public ClansRanking as(String alias) {
        return new ClansRanking(DSL.name(alias), this);
    }

    @Override
    public ClansRanking as(Name alias) {
        return new ClansRanking(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClansRanking rename(String name) {
        return new ClansRanking(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClansRanking rename(Name name) {
        return new ClansRanking(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
