/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.tables;


import com.kalaazu.persistence.database.Indexes;
import com.kalaazu.persistence.database.Kalaazu;
import com.kalaazu.persistence.database.Keys;
import com.kalaazu.persistence.database.records.GalaxygatesStagesSpawnsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Many to many relations for galaxygates_stages and galaxygates_spawns.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GalaxygatesStagesSpawns extends TableImpl<GalaxygatesStagesSpawnsRecord> {

    /**
     * The reference instance of <code>kalaazu.galaxygates_stages_spawns</code>
     */
    public static final GalaxygatesStagesSpawns GALAXYGATES_STAGES_SPAWNS = new GalaxygatesStagesSpawns();
    private static final long serialVersionUID = -1079665835;
    /**
     * The column <code>kalaazu.galaxygates_stages_spawns.id</code>. Primary Key.
     */
    public final TableField<GalaxygatesStagesSpawnsRecord, Integer> ID = createField(
            DSL.name("id"),
            org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true),
            this,
            "Primary Key."
    );
    /**
     * The column <code>kalaazu.galaxygates_stages_spawns.galaxygates_stages_id</code>.
     */
    public final TableField<GalaxygatesStagesSpawnsRecord, Integer> GALAXYGATES_STAGES_ID = createField(DSL.name(
            "galaxygates_stages_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>kalaazu.galaxygates_stages_spawns.galaxygates_spawns_id</code>.
     */
    public final TableField<GalaxygatesStagesSpawnsRecord, Integer> GALAXYGATES_SPAWNS_ID = createField(DSL.name(
            "galaxygates_spawns_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>kalaazu.galaxygates_stages_spawns</code> table reference
     */
    public GalaxygatesStagesSpawns() {
        this(DSL.name("galaxygates_stages_spawns"), null);
    }

    /**
     * Create an aliased <code>kalaazu.galaxygates_stages_spawns</code> table reference
     */
    public GalaxygatesStagesSpawns(String alias) {
        this(DSL.name(alias), GALAXYGATES_STAGES_SPAWNS);
    }

    /**
     * Create an aliased <code>kalaazu.galaxygates_stages_spawns</code> table reference
     */
    public GalaxygatesStagesSpawns(Name alias) {
        this(alias, GALAXYGATES_STAGES_SPAWNS);
    }

    private GalaxygatesStagesSpawns(Name alias, Table<GalaxygatesStagesSpawnsRecord> aliased) {
        this(alias, aliased, null);
    }

    private GalaxygatesStagesSpawns(Name alias, Table<GalaxygatesStagesSpawnsRecord> aliased, Field<?>[] parameters) {
        super(
                alias,
                null,
                aliased,
                parameters,
                DSL.comment("Many to many relations for galaxygates_stages and galaxygates_spawns.")
        );
    }

    public <O extends Record> GalaxygatesStagesSpawns(
            Table<O> child, ForeignKey<O, GalaxygatesStagesSpawnsRecord> key
    ) {
        super(child, key, GALAXYGATES_STAGES_SPAWNS);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GalaxygatesStagesSpawnsRecord> getRecordType() {
        return GalaxygatesStagesSpawnsRecord.class;
    }

    @Override
    public Schema getSchema() {
        return Kalaazu.KALAAZU;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(
                Indexes.GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_SPAWNS_ID_IDX,
                Indexes.GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_STAGES_ID_IDX,
                Indexes.GALAXYGATES_STAGES_SPAWNS_PRIMARY
        );
    }

    @Override
    public Identity<GalaxygatesStagesSpawnsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GALAXYGATES_STAGES_SPAWNS;
    }

    @Override
    public UniqueKey<GalaxygatesStagesSpawnsRecord> getPrimaryKey() {
        return Keys.KEY_GALAXYGATES_STAGES_SPAWNS_PRIMARY;
    }

    @Override
    public List<UniqueKey<GalaxygatesStagesSpawnsRecord>> getKeys() {
        return Arrays.<UniqueKey<GalaxygatesStagesSpawnsRecord>>asList(Keys.KEY_GALAXYGATES_STAGES_SPAWNS_PRIMARY);
    }

    @Override
    public List<ForeignKey<GalaxygatesStagesSpawnsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GalaxygatesStagesSpawnsRecord, ?>>asList(
                Keys.GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_STAGES,
                Keys.GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_SPAWNS
        );
    }

    public GalaxygatesStages galaxygatesStages() {
        return new GalaxygatesStages(this, Keys.GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_STAGES);
    }

    public GalaxygatesSpawns galaxygatesSpawns() {
        return new GalaxygatesSpawns(this, Keys.GALAXYGATES_STAGES_SPAWNS_GALAXYGATES_SPAWNS);
    }

    @Override
    public GalaxygatesStagesSpawns as(String alias) {
        return new GalaxygatesStagesSpawns(DSL.name(alias), this);
    }

    @Override
    public GalaxygatesStagesSpawns as(Name alias) {
        return new GalaxygatesStagesSpawns(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GalaxygatesStagesSpawns rename(String name) {
        return new GalaxygatesStagesSpawns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GalaxygatesStagesSpawns rename(Name name) {
        return new GalaxygatesStagesSpawns(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
