/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.tables;


import com.kalaazu.persistence.database.Indexes;
import com.kalaazu.persistence.database.Kalaazu;
import com.kalaazu.persistence.database.Keys;
import com.kalaazu.persistence.database.records.RewardsQuestsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Many to many relations.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RewardsQuests extends TableImpl<RewardsQuestsRecord> {

    /**
     * The reference instance of <code>kalaazu.rewards_quests</code>
     */
    public static final RewardsQuests REWARDS_QUESTS = new RewardsQuests();
    private static final long serialVersionUID = 1291237193;
    /**
     * The column <code>kalaazu.rewards_quests.id</code>. Primary Key.
     */
    public final TableField<RewardsQuestsRecord, Short> ID = createField(
            DSL.name("id"),
            org.jooq.impl.SQLDataType.SMALLINT.nullable(false).identity(true),
            this,
            "Primary Key."
    );
    /**
     * The column <code>kalaazu.rewards_quests.quests_id</code>. Quest ID.
     */
    public final TableField<RewardsQuestsRecord, Short> QUESTS_ID = createField(
            DSL.name("quests_id"),
            org.jooq.impl.SQLDataType.SMALLINT.nullable(false),
            this,
            "Quest ID."
    );
    /**
     * The column <code>kalaazu.rewards_quests.rewards_id</code>. Reward to award.
     */
    public final TableField<RewardsQuestsRecord, Short> REWARDS_ID = createField(
            DSL.name("rewards_id"),
            org.jooq.impl.SQLDataType.SMALLINT.nullable(false),
            this,
            "Reward to award."
    );

    /**
     * Create a <code>kalaazu.rewards_quests</code> table reference
     */
    public RewardsQuests() {
        this(DSL.name("rewards_quests"), null);
    }

    /**
     * Create an aliased <code>kalaazu.rewards_quests</code> table reference
     */
    public RewardsQuests(String alias) {
        this(DSL.name(alias), REWARDS_QUESTS);
    }

    /**
     * Create an aliased <code>kalaazu.rewards_quests</code> table reference
     */
    public RewardsQuests(Name alias) {
        this(alias, REWARDS_QUESTS);
    }

    private RewardsQuests(Name alias, Table<RewardsQuestsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RewardsQuests(Name alias, Table<RewardsQuestsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Many to many relations."));
    }

    public <O extends Record> RewardsQuests(Table<O> child, ForeignKey<O, RewardsQuestsRecord> key) {
        super(child, key, REWARDS_QUESTS);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RewardsQuestsRecord> getRecordType() {
        return RewardsQuestsRecord.class;
    }

    @Override
    public Schema getSchema() {
        return Kalaazu.KALAAZU;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(
                Indexes.REWARDS_QUESTS_PRIMARY,
                Indexes.REWARDS_QUESTS_REWARDS_QUESTS_QUESTS_ID_IDX,
                Indexes.REWARDS_QUESTS_REWARDS_QUESTS_REWARDS_ID_IDX
        );
    }

    @Override
    public Identity<RewardsQuestsRecord, Short> getIdentity() {
        return Keys.IDENTITY_REWARDS_QUESTS;
    }

    @Override
    public UniqueKey<RewardsQuestsRecord> getPrimaryKey() {
        return Keys.KEY_REWARDS_QUESTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<RewardsQuestsRecord>> getKeys() {
        return Arrays.<UniqueKey<RewardsQuestsRecord>>asList(Keys.KEY_REWARDS_QUESTS_PRIMARY);
    }

    @Override
    public List<ForeignKey<RewardsQuestsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RewardsQuestsRecord, ?>>asList(
                Keys.REWARDS_QUESTS_QUESTS,
                Keys.REWARDS_QUESTS_REWARDS
        );
    }

    public Quests quests() {
        return new Quests(this, Keys.REWARDS_QUESTS_QUESTS);
    }

    public Rewards rewards() {
        return new Rewards(this, Keys.REWARDS_QUESTS_REWARDS);
    }

    @Override
    public RewardsQuests as(String alias) {
        return new RewardsQuests(DSL.name(alias), this);
    }

    @Override
    public RewardsQuests as(Name alias) {
        return new RewardsQuests(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RewardsQuests rename(String name) {
        return new RewardsQuests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RewardsQuests rename(Name name) {
        return new RewardsQuests(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Short, Short, Short> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
