/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.records;


import com.kalaazu.persistence.database.tables.InvitationCodes;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Contains the invitation codes that can be used for registering.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class InvitationCodesRecord extends UpdatableRecordImpl<InvitationCodesRecord> implements Record3<Short, String, Byte> {

    private static final long serialVersionUID = 253089819;

    /**
     * Create a detached InvitationCodesRecord
     */
    public InvitationCodesRecord() {
        super(InvitationCodes.INVITATION_CODES);
    }

    /**
     * Create a detached, initialised InvitationCodesRecord
     */
    public InvitationCodesRecord(Short id, String code, Byte limit) {
        super(InvitationCodes.INVITATION_CODES);

        set(0, id);
        set(1, code);
        set(2, limit);
    }

    /**
     * Getter for <code>kalaazu.invitation_codes.id</code>. Primary Key.
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>kalaazu.invitation_codes.id</code>. Primary Key.
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.invitation_codes.code</code>. The invitation code.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kalaazu.invitation_codes.code</code>. The invitation code.
     */
    public void setCode(String value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.invitation_codes.limit</code>. Amount of times the code can be used.
     */
    public Byte getLimit() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.invitation_codes.limit</code>. Amount of times the code can be used.
     */
    public void setLimit(Byte value) {
        set(2, value);
    }

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<Short, String, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Short, String, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return InvitationCodes.INVITATION_CODES.ID;
    }

    @Override
    public Field<String> field2() {
        return InvitationCodes.INVITATION_CODES.CODE;
    }

    @Override
    public Field<Byte> field3() {
        return InvitationCodes.INVITATION_CODES.LIMIT;
    }

    @Override
    public Short component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public Byte component3() {
        return getLimit();
    }

    @Override
    public Short value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public Byte value3() {
        return getLimit();
    }

    @Override
    public InvitationCodesRecord value1(Short value) {
        setId(value);
        return this;
    }

    @Override
    public InvitationCodesRecord value2(String value) {
        setCode(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public InvitationCodesRecord value3(Byte value) {
        setLimit(value);
        return this;
    }

    @Override
    public InvitationCodesRecord values(Short value1, String value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
