/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.records;


import com.kalaazu.persistence.database.tables.ModeratorsRoles;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Moderator's roles.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ModeratorsRolesRecord extends UpdatableRecordImpl<ModeratorsRolesRecord> implements Record4<Byte, String, Byte, Byte> {

    private static final long serialVersionUID = 1803153144;

    /**
     * Create a detached ModeratorsRolesRecord
     */
    public ModeratorsRolesRecord() {
        super(ModeratorsRoles.MODERATORS_ROLES);
    }

    /**
     * Create a detached, initialised ModeratorsRolesRecord
     */
    public ModeratorsRolesRecord(Byte id, String name, Byte moderatorsRolesId, Byte priority) {
        super(ModeratorsRoles.MODERATORS_ROLES);

        set(0, id);
        set(1, name);
        set(2, moderatorsRolesId);
        set(3, priority);
    }

    /**
     * Getter for <code>kalaazu.moderators_roles.id</code>. Primary Key.
     */
    public Byte getId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>kalaazu.moderators_roles.id</code>. Primary Key.
     */
    public void setId(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.moderators_roles.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kalaazu.moderators_roles.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.moderators_roles.moderators_roles_id</code>. Parent role.
     */
    public Byte getModeratorsRolesId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.moderators_roles.moderators_roles_id</code>. Parent role.
     */
    public void setModeratorsRolesId(Byte value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.moderators_roles.priority</code>.
     */
    public Byte getPriority() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.moderators_roles.priority</code>.
     */
    public void setPriority(Byte value) {
        set(3, value);
    }

    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    @Override
    public Row4<Byte, String, Byte, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Byte, String, Byte, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Byte> field1() {
        return ModeratorsRoles.MODERATORS_ROLES.ID;
    }

    @Override
    public Field<String> field2() {
        return ModeratorsRoles.MODERATORS_ROLES.NAME;
    }

    @Override
    public Field<Byte> field3() {
        return ModeratorsRoles.MODERATORS_ROLES.MODERATORS_ROLES_ID;
    }

    @Override
    public Field<Byte> field4() {
        return ModeratorsRoles.MODERATORS_ROLES.PRIORITY;
    }

    @Override
    public Byte component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Byte component3() {
        return getModeratorsRolesId();
    }

    @Override
    public Byte component4() {
        return getPriority();
    }

    @Override
    public Byte value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Byte value3() {
        return getModeratorsRolesId();
    }

    @Override
    public Byte value4() {
        return getPriority();
    }

    @Override
    public ModeratorsRolesRecord value1(Byte value) {
        setId(value);
        return this;
    }

    @Override
    public ModeratorsRolesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ModeratorsRolesRecord value3(Byte value) {
        setModeratorsRolesId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public ModeratorsRolesRecord value4(Byte value) {
        setPriority(value);
        return this;
    }

    @Override
    public ModeratorsRolesRecord values(Byte value1, String value2, Byte value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
