/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.records;


import com.kalaazu.persistence.database.tables.RewardsNpcs;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Many to many relations.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RewardsNpcsRecord extends UpdatableRecordImpl<RewardsNpcsRecord> implements Record3<Short, Byte, Short> {

    private static final long serialVersionUID = 913287800;

    /**
     * Create a detached RewardsNpcsRecord
     */
    public RewardsNpcsRecord() {
        super(RewardsNpcs.REWARDS_NPCS);
    }

    /**
     * Create a detached, initialised RewardsNpcsRecord
     */
    public RewardsNpcsRecord(Short id, Byte npcsId, Short rewardsId) {
        super(RewardsNpcs.REWARDS_NPCS);

        set(0, id);
        set(1, npcsId);
        set(2, rewardsId);
    }

    /**
     * Getter for <code>kalaazu.rewards_npcs.id</code>. Primary Key.
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>kalaazu.rewards_npcs.id</code>. Primary Key.
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.rewards_npcs.npcs_id</code>. NPC ID.
     */
    public Byte getNpcsId() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>kalaazu.rewards_npcs.npcs_id</code>. NPC ID.
     */
    public void setNpcsId(Byte value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.rewards_npcs.rewards_id</code>. Reward to award.
     */
    public Short getRewardsId() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.rewards_npcs.rewards_id</code>. Reward to award.
     */
    public void setRewardsId(Short value) {
        set(2, value);
    }

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<Short, Byte, Short> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Short, Byte, Short> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return RewardsNpcs.REWARDS_NPCS.ID;
    }

    @Override
    public Field<Byte> field2() {
        return RewardsNpcs.REWARDS_NPCS.NPCS_ID;
    }

    @Override
    public Field<Short> field3() {
        return RewardsNpcs.REWARDS_NPCS.REWARDS_ID;
    }

    @Override
    public Short component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getNpcsId();
    }

    @Override
    public Short component3() {
        return getRewardsId();
    }

    @Override
    public Short value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getNpcsId();
    }

    @Override
    public Short value3() {
        return getRewardsId();
    }

    @Override
    public RewardsNpcsRecord value1(Short value) {
        setId(value);
        return this;
    }

    @Override
    public RewardsNpcsRecord value2(Byte value) {
        setNpcsId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public RewardsNpcsRecord value3(Short value) {
        setRewardsId(value);
        return this;
    }

    @Override
    public RewardsNpcsRecord values(Short value1, Byte value2, Short value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
