/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.AccountsSkills;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Skilltree for the account.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AccountsSkillsRecord extends UpdatableRecordImpl<AccountsSkillsRecord> implements Record4<Integer, Integer, Byte, Short> {

    private static final long serialVersionUID = -517319197;

    /**
     * Create a detached AccountsSkillsRecord
     */
    public AccountsSkillsRecord() {
        super(AccountsSkills.ACCOUNTS_SKILLS);
    }

    /**
     * Create a detached, initialised AccountsSkillsRecord
     */
    public AccountsSkillsRecord(Integer id, Integer accountsId, Byte skilltreeSkillsId, Short skilltreeLevelsId) {
        super(AccountsSkills.ACCOUNTS_SKILLS);

        set(0, id);
        set(1, accountsId);
        set(2, skilltreeSkillsId);
        set(3, skilltreeLevelsId);
    }

    /**
     * Getter for <code>kalaazu.accounts_skills.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.accounts_skills.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_skills.accounts_id</code>. Account ID.
     */
    public Integer getAccountsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.accounts_skills.accounts_id</code>. Account ID.
     */
    public void setAccountsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_skills.skilltree_skills_id</code>. Skill ID.
     */
    public Byte getSkilltreeSkillsId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.accounts_skills.skilltree_skills_id</code>. Skill ID.
     */
    public void setSkilltreeSkillsId(Byte value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.accounts_skills.skilltree_levels_id</code>. Skill level.
     */
    public Short getSkilltreeLevelsId() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.accounts_skills.skilltree_levels_id</code>. Skill level.
     */
    public void setSkilltreeLevelsId(Short value) {
        set(3, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row4<Integer, Integer, Byte, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Byte, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AccountsSkills.ACCOUNTS_SKILLS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AccountsSkills.ACCOUNTS_SKILLS.ACCOUNTS_ID;
    }

    @Override
    public Field<Byte> field3() {
        return AccountsSkills.ACCOUNTS_SKILLS.SKILLTREE_SKILLS_ID;
    }

    @Override
    public Field<Short> field4() {
        return AccountsSkills.ACCOUNTS_SKILLS.SKILLTREE_LEVELS_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAccountsId();
    }

    @Override
    public Byte component3() {
        return getSkilltreeSkillsId();
    }

    @Override
    public Short component4() {
        return getSkilltreeLevelsId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAccountsId();
    }

    @Override
    public Byte value3() {
        return getSkilltreeSkillsId();
    }

    @Override
    public Short value4() {
        return getSkilltreeLevelsId();
    }

    @Override
    public AccountsSkillsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AccountsSkillsRecord value2(Integer value) {
        setAccountsId(value);
        return this;
    }

    @Override
    public AccountsSkillsRecord value3(Byte value) {
        setSkilltreeSkillsId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AccountsSkillsRecord value4(Short value) {
        setSkilltreeLevelsId(value);
        return this;
    }

    @Override
    public AccountsSkillsRecord values(Integer value1, Integer value2, Byte value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
