/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.AccountsConfigurationsAccountsItems;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Items of the configuration.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AccountsConfigurationsAccountsItemsRecord extends UpdatableRecordImpl<AccountsConfigurationsAccountsItemsRecord> implements Record5<Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1637427507;

    /**
     * Create a detached AccountsConfigurationsAccountsItemsRecord
     */
    public AccountsConfigurationsAccountsItemsRecord() {
        super(AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS);
    }

    /**
     * Create a detached, initialised AccountsConfigurationsAccountsItemsRecord
     */
    public AccountsConfigurationsAccountsItemsRecord(
            Integer id, Integer accountsConfigurationsId, Integer accountsItemsId, Integer accountsDronesId,
            Integer accountsPetsId
    ) {
        super(AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS);

        set(0, id);
        set(1, accountsConfigurationsId);
        set(2, accountsItemsId);
        set(3, accountsDronesId);
        set(4, accountsPetsId);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations_accounts_items.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations_accounts_items.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations_accounts_items.accounts_configurations_id</code>.
     */
    public Integer getAccountsConfigurationsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations_accounts_items.accounts_configurations_id</code>.
     */
    public void setAccountsConfigurationsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations_accounts_items.accounts_items_id</code>.
     */
    public Integer getAccountsItemsId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations_accounts_items.accounts_items_id</code>.
     */
    public void setAccountsItemsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations_accounts_items.accounts_drones_id</code>.
     */
    public Integer getAccountsDronesId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations_accounts_items.accounts_drones_id</code>.
     */
    public void setAccountsDronesId(Integer value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.accounts_configurations_accounts_items.accounts_pets_id</code>.
     */
    public Integer getAccountsPetsId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.accounts_configurations_accounts_items.accounts_pets_id</code>.
     */
    public void setAccountsPetsId(Integer value) {
        set(4, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS.ACCOUNTS_CONFIGURATIONS_ID;
    }

    @Override
    public Field<Integer> field3() {
        return AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS.ACCOUNTS_ITEMS_ID;
    }

    @Override
    public Field<Integer> field4() {
        return AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS.ACCOUNTS_DRONES_ID;
    }

    @Override
    public Field<Integer> field5() {
        return AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS.ACCOUNTS_PETS_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAccountsConfigurationsId();
    }

    @Override
    public Integer component3() {
        return getAccountsItemsId();
    }

    @Override
    public Integer component4() {
        return getAccountsDronesId();
    }

    @Override
    public Integer component5() {
        return getAccountsPetsId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAccountsConfigurationsId();
    }

    @Override
    public Integer value3() {
        return getAccountsItemsId();
    }

    @Override
    public Integer value4() {
        return getAccountsDronesId();
    }

    @Override
    public Integer value5() {
        return getAccountsPetsId();
    }

    @Override
    public AccountsConfigurationsAccountsItemsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AccountsConfigurationsAccountsItemsRecord value2(Integer value) {
        setAccountsConfigurationsId(value);
        return this;
    }

    @Override
    public AccountsConfigurationsAccountsItemsRecord value3(Integer value) {
        setAccountsItemsId(value);
        return this;
    }

    @Override
    public AccountsConfigurationsAccountsItemsRecord value4(Integer value) {
        setAccountsDronesId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AccountsConfigurationsAccountsItemsRecord value5(Integer value) {
        setAccountsPetsId(value);
        return this;
    }

    @Override
    public AccountsConfigurationsAccountsItemsRecord values(
            Integer value1, Integer value2, Integer value3, Integer value4, Integer value5
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
