/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.AccountsConfigurations;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Configurations of the accounts.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AccountsConfigurationsRecord extends UpdatableRecordImpl<AccountsConfigurationsRecord> implements Record7<Integer, Integer, Byte, String, Integer, Short, Integer> {

    private static final long serialVersionUID = -957891515;

    /**
     * Create a detached AccountsConfigurationsRecord
     */
    public AccountsConfigurationsRecord() {
        super(AccountsConfigurations.ACCOUNTS_CONFIGURATIONS);
    }

    /**
     * Create a detached, initialised AccountsConfigurationsRecord
     */
    public AccountsConfigurationsRecord(
            Integer id, Integer accountsHangarsId, Byte configurationId, String name, Integer shield, Short speed,
            Integer damage
    ) {
        super(AccountsConfigurations.ACCOUNTS_CONFIGURATIONS);

        set(0, id);
        set(1, accountsHangarsId);
        set(2, configurationId);
        set(3, name);
        set(4, shield);
        set(5, speed);
        set(6, damage);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations.accounts_hangars_id</code>.
     */
    public Integer getAccountsHangarsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations.accounts_hangars_id</code>.
     */
    public void setAccountsHangarsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations.configuration_id</code>. Configuration ID (1 or 2 (or 3)).
     */
    public Byte getConfigurationId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations.configuration_id</code>. Configuration ID (1 or 2 (or 3)).
     */
    public void setConfigurationId(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations.shield</code>. Shield available in the configuration.
     */
    public Integer getShield() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations.shield</code>. Shield available in the configuration.
     */
    public void setShield(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_configurations.speed</code>. Speed available in the configuration.
     */
    public Short getSpeed() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>kalaazu.accounts_configurations.speed</code>. Speed available in the configuration.
     */
    public void setSpeed(Short value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.accounts_configurations.damage</code>. Damage available in the configuration.
     */
    public Integer getDamage() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.accounts_configurations.damage</code>. Damage available in the configuration.
     */
    public void setDamage(Integer value) {
        set(6, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row7<Integer, Integer, Byte, String, Integer, Short, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Byte, String, Integer, Short, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AccountsConfigurations.ACCOUNTS_CONFIGURATIONS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AccountsConfigurations.ACCOUNTS_CONFIGURATIONS.ACCOUNTS_HANGARS_ID;
    }

    @Override
    public Field<Byte> field3() {
        return AccountsConfigurations.ACCOUNTS_CONFIGURATIONS.CONFIGURATION_ID;
    }

    @Override
    public Field<String> field4() {
        return AccountsConfigurations.ACCOUNTS_CONFIGURATIONS.NAME;
    }

    @Override
    public Field<Integer> field5() {
        return AccountsConfigurations.ACCOUNTS_CONFIGURATIONS.SHIELD;
    }

    @Override
    public Field<Short> field6() {
        return AccountsConfigurations.ACCOUNTS_CONFIGURATIONS.SPEED;
    }

    @Override
    public Field<Integer> field7() {
        return AccountsConfigurations.ACCOUNTS_CONFIGURATIONS.DAMAGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAccountsHangarsId();
    }

    @Override
    public Byte component3() {
        return getConfigurationId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Integer component5() {
        return getShield();
    }

    @Override
    public Short component6() {
        return getSpeed();
    }

    @Override
    public Integer component7() {
        return getDamage();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAccountsHangarsId();
    }

    @Override
    public Byte value3() {
        return getConfigurationId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Integer value5() {
        return getShield();
    }

    @Override
    public Short value6() {
        return getSpeed();
    }

    @Override
    public Integer value7() {
        return getDamage();
    }

    @Override
    public AccountsConfigurationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AccountsConfigurationsRecord value2(Integer value) {
        setAccountsHangarsId(value);
        return this;
    }

    @Override
    public AccountsConfigurationsRecord value3(Byte value) {
        setConfigurationId(value);
        return this;
    }

    @Override
    public AccountsConfigurationsRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public AccountsConfigurationsRecord value5(Integer value) {
        setShield(value);
        return this;
    }

    @Override
    public AccountsConfigurationsRecord value6(Short value) {
        setSpeed(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AccountsConfigurationsRecord value7(Integer value) {
        setDamage(value);
        return this;
    }

    @Override
    public AccountsConfigurationsRecord values(
            Integer value1, Integer value2, Byte value3, String value4, Integer value5, Short value6, Integer value7
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
