/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.AccountsDestroys;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Account's destroy history.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AccountsDestroysRecord extends UpdatableRecordImpl<AccountsDestroysRecord> implements Record5<Integer, Integer, Byte, Short, Short> {

    private static final long serialVersionUID = -705830394;

    /**
     * Create a detached AccountsDestroysRecord
     */
    public AccountsDestroysRecord() {
        super(AccountsDestroys.ACCOUNTS_DESTROYS);
    }

    /**
     * Create a detached, initialised AccountsDestroysRecord
     */
    public AccountsDestroysRecord(Integer id, Integer accountsId, Byte shipsId, Short points, Short amount) {
        super(AccountsDestroys.ACCOUNTS_DESTROYS);

        set(0, id);
        set(1, accountsId);
        set(2, shipsId);
        set(3, points);
        set(4, amount);
    }

    /**
     * Getter for <code>kalaazu.accounts_destroys.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.accounts_destroys.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_destroys.accounts_id</code>.
     */
    public Integer getAccountsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.accounts_destroys.accounts_id</code>.
     */
    public void setAccountsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_destroys.ships_id</code>.
     */
    public Byte getShipsId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.accounts_destroys.ships_id</code>.
     */
    public void setShipsId(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_destroys.points</code>. Rank points received for destroying this ship.
     */
    public Short getPoints() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>kalaazu.accounts_destroys.points</code>. Rank points received for destroying this ship.
     */
    public void setPoints(Short value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.accounts_destroys.amount</code>. Times this ship has been destroyed
     */
    public Short getAmount() {
        return (Short) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.accounts_destroys.amount</code>. Times this ship has been destroyed
     */
    public void setAmount(Short value) {
        set(4, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row5<Integer, Integer, Byte, Short, Short> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Byte, Short, Short> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AccountsDestroys.ACCOUNTS_DESTROYS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AccountsDestroys.ACCOUNTS_DESTROYS.ACCOUNTS_ID;
    }

    @Override
    public Field<Byte> field3() {
        return AccountsDestroys.ACCOUNTS_DESTROYS.SHIPS_ID;
    }

    @Override
    public Field<Short> field4() {
        return AccountsDestroys.ACCOUNTS_DESTROYS.POINTS;
    }

    @Override
    public Field<Short> field5() {
        return AccountsDestroys.ACCOUNTS_DESTROYS.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAccountsId();
    }

    @Override
    public Byte component3() {
        return getShipsId();
    }

    @Override
    public Short component4() {
        return getPoints();
    }

    @Override
    public Short component5() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAccountsId();
    }

    @Override
    public Byte value3() {
        return getShipsId();
    }

    @Override
    public Short value4() {
        return getPoints();
    }

    @Override
    public Short value5() {
        return getAmount();
    }

    @Override
    public AccountsDestroysRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AccountsDestroysRecord value2(Integer value) {
        setAccountsId(value);
        return this;
    }

    @Override
    public AccountsDestroysRecord value3(Byte value) {
        setShipsId(value);
        return this;
    }

    @Override
    public AccountsDestroysRecord value4(Short value) {
        setPoints(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AccountsDestroysRecord value5(Short value) {
        setAmount(value);
        return this;
    }

    @Override
    public AccountsDestroysRecord values(Integer value1, Integer value2, Byte value3, Short value4, Short value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
