/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.AccountsPets;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * Account's PETs.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AccountsPetsRecord extends UpdatableRecordImpl<AccountsPetsRecord> implements Record15<Integer, Integer, Byte, String, Integer, Integer, Integer, Byte, Byte, Byte, Byte, Byte, Byte, Byte, Byte> {

    private static final long serialVersionUID = -1956911620;

    /**
     * Create a detached AccountsPetsRecord
     */
    public AccountsPetsRecord() {
        super(AccountsPets.ACCOUNTS_PETS);
    }

    /**
     * Create a detached, initialised AccountsPetsRecord
     */
    public AccountsPetsRecord(
            Integer id, Integer accountsId, Byte levelsId, String name, Integer experience, Integer fuel,
            Integer health, Byte slotsLasersTotal, Byte slotsLasersAvailable, Byte slotsGeneratorsTotal,
            Byte slotsGeneratorsAvailable, Byte slotsProtocolsTotal, Byte slotsProtocolsAvailable, Byte slotsGearsTotal,
            Byte slotsGearsAvailable
    ) {
        super(AccountsPets.ACCOUNTS_PETS);

        set(0, id);
        set(1, accountsId);
        set(2, levelsId);
        set(3, name);
        set(4, experience);
        set(5, fuel);
        set(6, health);
        set(7, slotsLasersTotal);
        set(8, slotsLasersAvailable);
        set(9, slotsGeneratorsTotal);
        set(10, slotsGeneratorsAvailable);
        set(11, slotsProtocolsTotal);
        set(12, slotsProtocolsAvailable);
        set(13, slotsGearsTotal);
        set(14, slotsGearsAvailable);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.accounts_id</code>.
     */
    public Integer getAccountsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.accounts_id</code>.
     */
    public void setAccountsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.levels_id</code>.
     */
    public Byte getLevelsId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.levels_id</code>.
     */
    public void setLevelsId(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.experience</code>.
     */
    public Integer getExperience() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.experience</code>.
     */
    public void setExperience(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.fuel</code>.
     */
    public Integer getFuel() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.fuel</code>.
     */
    public void setFuel(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.health</code>.
     */
    public Integer getHealth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.health</code>.
     */
    public void setHealth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_lasers_total</code>.
     */
    public Byte getSlotsLasersTotal() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_lasers_total</code>.
     */
    public void setSlotsLasersTotal(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_lasers_available</code>.
     */
    public Byte getSlotsLasersAvailable() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_lasers_available</code>.
     */
    public void setSlotsLasersAvailable(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_generators_total</code>.
     */
    public Byte getSlotsGeneratorsTotal() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_generators_total</code>.
     */
    public void setSlotsGeneratorsTotal(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_generators_available</code>.
     */
    public Byte getSlotsGeneratorsAvailable() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_generators_available</code>.
     */
    public void setSlotsGeneratorsAvailable(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_protocols_total</code>.
     */
    public Byte getSlotsProtocolsTotal() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_protocols_total</code>.
     */
    public void setSlotsProtocolsTotal(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_protocols_available</code>.
     */
    public Byte getSlotsProtocolsAvailable() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_protocols_available</code>.
     */
    public void setSlotsProtocolsAvailable(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_gears_total</code>.
     */
    public Byte getSlotsGearsTotal() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_gears_total</code>.
     */
    public void setSlotsGearsTotal(Byte value) {
        set(13, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.accounts_pets.slots_gears_available</code>.
     */
    public Byte getSlotsGearsAvailable() {
        return (Byte) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.accounts_pets.slots_gears_available</code>.
     */
    public void setSlotsGearsAvailable(Byte value) {
        set(14, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row15<Integer, Integer, Byte, String, Integer, Integer, Integer, Byte, Byte, Byte, Byte, Byte, Byte, Byte, Byte> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, Integer, Byte, String, Integer, Integer, Integer, Byte, Byte, Byte, Byte, Byte, Byte, Byte, Byte> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AccountsPets.ACCOUNTS_PETS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AccountsPets.ACCOUNTS_PETS.ACCOUNTS_ID;
    }

    @Override
    public Field<Byte> field3() {
        return AccountsPets.ACCOUNTS_PETS.LEVELS_ID;
    }

    @Override
    public Field<String> field4() {
        return AccountsPets.ACCOUNTS_PETS.NAME;
    }

    @Override
    public Field<Integer> field5() {
        return AccountsPets.ACCOUNTS_PETS.EXPERIENCE;
    }

    @Override
    public Field<Integer> field6() {
        return AccountsPets.ACCOUNTS_PETS.FUEL;
    }

    @Override
    public Field<Integer> field7() {
        return AccountsPets.ACCOUNTS_PETS.HEALTH;
    }

    @Override
    public Field<Byte> field8() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_LASERS_TOTAL;
    }

    @Override
    public Field<Byte> field9() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_LASERS_AVAILABLE;
    }

    @Override
    public Field<Byte> field10() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_GENERATORS_TOTAL;
    }

    @Override
    public Field<Byte> field11() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_GENERATORS_AVAILABLE;
    }

    @Override
    public Field<Byte> field12() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_PROTOCOLS_TOTAL;
    }

    @Override
    public Field<Byte> field13() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_PROTOCOLS_AVAILABLE;
    }

    @Override
    public Field<Byte> field14() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_GEARS_TOTAL;
    }

    @Override
    public Field<Byte> field15() {
        return AccountsPets.ACCOUNTS_PETS.SLOTS_GEARS_AVAILABLE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAccountsId();
    }

    @Override
    public Byte component3() {
        return getLevelsId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Integer component5() {
        return getExperience();
    }

    @Override
    public Integer component6() {
        return getFuel();
    }

    @Override
    public Integer component7() {
        return getHealth();
    }

    @Override
    public Byte component8() {
        return getSlotsLasersTotal();
    }

    @Override
    public Byte component9() {
        return getSlotsLasersAvailable();
    }

    @Override
    public Byte component10() {
        return getSlotsGeneratorsTotal();
    }

    @Override
    public Byte component11() {
        return getSlotsGeneratorsAvailable();
    }

    @Override
    public Byte component12() {
        return getSlotsProtocolsTotal();
    }

    @Override
    public Byte component13() {
        return getSlotsProtocolsAvailable();
    }

    @Override
    public Byte component14() {
        return getSlotsGearsTotal();
    }

    @Override
    public Byte component15() {
        return getSlotsGearsAvailable();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAccountsId();
    }

    @Override
    public Byte value3() {
        return getLevelsId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Integer value5() {
        return getExperience();
    }

    @Override
    public Integer value6() {
        return getFuel();
    }

    @Override
    public Integer value7() {
        return getHealth();
    }

    @Override
    public Byte value8() {
        return getSlotsLasersTotal();
    }

    @Override
    public Byte value9() {
        return getSlotsLasersAvailable();
    }

    @Override
    public Byte value10() {
        return getSlotsGeneratorsTotal();
    }

    @Override
    public Byte value11() {
        return getSlotsGeneratorsAvailable();
    }

    @Override
    public Byte value12() {
        return getSlotsProtocolsTotal();
    }

    @Override
    public Byte value13() {
        return getSlotsProtocolsAvailable();
    }

    @Override
    public Byte value14() {
        return getSlotsGearsTotal();
    }

    @Override
    public Byte value15() {
        return getSlotsGearsAvailable();
    }

    @Override
    public AccountsPetsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value2(Integer value) {
        setAccountsId(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value3(Byte value) {
        setLevelsId(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value5(Integer value) {
        setExperience(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value6(Integer value) {
        setFuel(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value7(Integer value) {
        setHealth(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value8(Byte value) {
        setSlotsLasersTotal(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value9(Byte value) {
        setSlotsLasersAvailable(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value10(Byte value) {
        setSlotsGeneratorsTotal(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value11(Byte value) {
        setSlotsGeneratorsAvailable(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value12(Byte value) {
        setSlotsProtocolsTotal(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value13(Byte value) {
        setSlotsProtocolsAvailable(value);
        return this;
    }

    @Override
    public AccountsPetsRecord value14(Byte value) {
        setSlotsGearsTotal(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AccountsPetsRecord value15(Byte value) {
        setSlotsGearsAvailable(value);
        return this;
    }

    @Override
    public AccountsPetsRecord values(
            Integer value1, Integer value2, Byte value3, String value4, Integer value5, Integer value6, Integer value7,
            Byte value8, Byte value9, Byte value10, Byte value11, Byte value12, Byte value13, Byte value14, Byte value15
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }
}
