/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.ClansBattlestationsItems;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Items equipped in the CBS.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClansBattlestationsItemsRecord extends UpdatableRecordImpl<ClansBattlestationsItemsRecord> implements Record5<Integer, Byte, Integer, Byte, Timestamp> {

    private static final long serialVersionUID = 1016281830;

    /**
     * Setter for <code>kalaazu.clans_battlestations_items.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.clans_battlestations_items.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.clans_battlestations_items.clans_battlestations_id</code>. CBS where item is equipped.
     */
    public void setClansBattlestationsId(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.clans_battlestations_items.clans_battlestations_id</code>. CBS where item is equipped.
     */
    public Byte getClansBattlestationsId() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>kalaazu.clans_battlestations_items.accounts_items_id</code>. Equipped item.
     */
    public void setAccountsItemsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.clans_battlestations_items.accounts_items_id</code>. Equipped item.
     */
    public Integer getAccountsItemsId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kalaazu.clans_battlestations_items.slot</code>. Position where the item is equipped (A = 9, B = 10).
     */
    public void setSlot(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.clans_battlestations_items.slot</code>. Position where the item is equipped (A = 9, B = 10).
     */
    public Byte getSlot() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kalaazu.clans_battlestations_items.date</code>. Date when the item was equipped.
     */
    public void setDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.clans_battlestations_items.date</code>. Date when the item was equipped.
     */
    public Timestamp getDate() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Byte, Integer, Byte, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Byte, Integer, Byte, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS.ID;
    }

    @Override
    public Field<Byte> field2() {
        return ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS.CLANS_BATTLESTATIONS_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS.ACCOUNTS_ITEMS_ID;
    }

    @Override
    public Field<Byte> field4() {
        return ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS.SLOT;
    }

    @Override
    public Field<Timestamp> field5() {
        return ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS.DATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getClansBattlestationsId();
    }

    @Override
    public Integer component3() {
        return getAccountsItemsId();
    }

    @Override
    public Byte component4() {
        return getSlot();
    }

    @Override
    public Timestamp component5() {
        return getDate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getClansBattlestationsId();
    }

    @Override
    public Integer value3() {
        return getAccountsItemsId();
    }

    @Override
    public Byte value4() {
        return getSlot();
    }

    @Override
    public Timestamp value5() {
        return getDate();
    }

    @Override
    public ClansBattlestationsItemsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClansBattlestationsItemsRecord value2(Byte value) {
        setClansBattlestationsId(value);
        return this;
    }

    @Override
    public ClansBattlestationsItemsRecord value3(Integer value) {
        setAccountsItemsId(value);
        return this;
    }

    @Override
    public ClansBattlestationsItemsRecord value4(Byte value) {
        setSlot(value);
        return this;
    }

    @Override
    public ClansBattlestationsItemsRecord value5(Timestamp value) {
        setDate(value);
        return this;
    }

    @Override
    public ClansBattlestationsItemsRecord values(Integer value1, Byte value2, Integer value3, Byte value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClansBattlestationsItemsRecord
     */
    public ClansBattlestationsItemsRecord() {
        super(ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS);
    }

    /**
     * Create a detached, initialised ClansBattlestationsItemsRecord
     */
    public ClansBattlestationsItemsRecord(Integer id, Byte clansBattlestationsId, Integer accountsItemsId, Byte slot, Timestamp date) {
        super(ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS);

        set(0, id);
        set(1, clansBattlestationsId);
        set(2, accountsItemsId);
        set(3, slot);
        set(4, date);
    }
}
