/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.MapsPortals;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Portals on map.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapsPortalsRecord extends UpdatableRecordImpl<MapsPortalsRecord> implements Record9<Byte, Byte, Byte, Long, Byte, Long, Byte, Byte, Byte> {

    private static final long serialVersionUID = -483572563;

    /**
     * Setter for <code>kalaazu.maps_portals.id</code>. Primary Key.
     */
    public void setId(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.id</code>. Primary Key.
     */
    public Byte getId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.levels_id</code>.
     */
    public void setLevelsId(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.levels_id</code>.
     */
    public Byte getLevelsId() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.maps_id</code>.
     */
    public void setMapsId(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.maps_id</code>.
     */
    public Byte getMapsId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.position</code>. Position on map.
     */
    public void setPosition(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.position</code>. Position on map.
     */
    public Long getPosition() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.target_maps_id</code>.
     */
    public void setTargetMapsId(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.target_maps_id</code>.
     */
    public Byte getTargetMapsId() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.target_position</code>. Target position.
     */
    public void setTargetPosition(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.target_position</code>. Target position.
     */
    public Long getTargetPosition() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.is_visible</code>.
     */
    public void setIsVisible(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.is_visible</code>.
     */
    public Byte getIsVisible() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.is_working</code>.
     */
    public void setIsWorking(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.is_working</code>.
     */
    public Byte getIsWorking() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>kalaazu.maps_portals.gfx</code>.
     */
    public void setGfx(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>kalaazu.maps_portals.gfx</code>.
     */
    public Byte getGfx() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Byte, Byte, Byte, Long, Byte, Long, Byte, Byte, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Byte, Byte, Byte, Long, Byte, Long, Byte, Byte, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Byte> field1() {
        return MapsPortals.MAPS_PORTALS.ID;
    }

    @Override
    public Field<Byte> field2() {
        return MapsPortals.MAPS_PORTALS.LEVELS_ID;
    }

    @Override
    public Field<Byte> field3() {
        return MapsPortals.MAPS_PORTALS.MAPS_ID;
    }

    @Override
    public Field<Long> field4() {
        return MapsPortals.MAPS_PORTALS.POSITION;
    }

    @Override
    public Field<Byte> field5() {
        return MapsPortals.MAPS_PORTALS.TARGET_MAPS_ID;
    }

    @Override
    public Field<Long> field6() {
        return MapsPortals.MAPS_PORTALS.TARGET_POSITION;
    }

    @Override
    public Field<Byte> field7() {
        return MapsPortals.MAPS_PORTALS.IS_VISIBLE;
    }

    @Override
    public Field<Byte> field8() {
        return MapsPortals.MAPS_PORTALS.IS_WORKING;
    }

    @Override
    public Field<Byte> field9() {
        return MapsPortals.MAPS_PORTALS.GFX;
    }

    @Override
    public Byte component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getLevelsId();
    }

    @Override
    public Byte component3() {
        return getMapsId();
    }

    @Override
    public Long component4() {
        return getPosition();
    }

    @Override
    public Byte component5() {
        return getTargetMapsId();
    }

    @Override
    public Long component6() {
        return getTargetPosition();
    }

    @Override
    public Byte component7() {
        return getIsVisible();
    }

    @Override
    public Byte component8() {
        return getIsWorking();
    }

    @Override
    public Byte component9() {
        return getGfx();
    }

    @Override
    public Byte value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getLevelsId();
    }

    @Override
    public Byte value3() {
        return getMapsId();
    }

    @Override
    public Long value4() {
        return getPosition();
    }

    @Override
    public Byte value5() {
        return getTargetMapsId();
    }

    @Override
    public Long value6() {
        return getTargetPosition();
    }

    @Override
    public Byte value7() {
        return getIsVisible();
    }

    @Override
    public Byte value8() {
        return getIsWorking();
    }

    @Override
    public Byte value9() {
        return getGfx();
    }

    @Override
    public MapsPortalsRecord value1(Byte value) {
        setId(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value2(Byte value) {
        setLevelsId(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value3(Byte value) {
        setMapsId(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value4(Long value) {
        setPosition(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value5(Byte value) {
        setTargetMapsId(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value6(Long value) {
        setTargetPosition(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value7(Byte value) {
        setIsVisible(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value8(Byte value) {
        setIsWorking(value);
        return this;
    }

    @Override
    public MapsPortalsRecord value9(Byte value) {
        setGfx(value);
        return this;
    }

    @Override
    public MapsPortalsRecord values(Byte value1, Byte value2, Byte value3, Long value4, Byte value5, Long value6, Byte value7, Byte value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MapsPortalsRecord
     */
    public MapsPortalsRecord() {
        super(MapsPortals.MAPS_PORTALS);
    }

    /**
     * Create a detached, initialised MapsPortalsRecord
     */
    public MapsPortalsRecord(Byte id, Byte levelsId, Byte mapsId, Long position, Byte targetMapsId, Long targetPosition, Byte isVisible, Byte isWorking, Byte gfx) {
        super(MapsPortals.MAPS_PORTALS);

        set(0, id);
        set(1, levelsId);
        set(2, mapsId);
        set(3, position);
        set(4, targetMapsId);
        set(5, targetPosition);
        set(6, isVisible);
        set(7, isWorking);
        set(8, gfx);
    }
}
