/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.QuestsConditions;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Quest's conditions.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestsConditionsRecord extends UpdatableRecordImpl<QuestsConditionsRecord> implements Record5<Integer, Integer, Short, Byte, String> {

    private static final long serialVersionUID = 1125655538;

    /**
     * Setter for <code>kalaazu.quests_conditions.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.quests_conditions.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.quests_conditions.quests_conditions_id</code>. Condition needed to unlock this condition.
     */
    public void setQuestsConditionsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.quests_conditions.quests_conditions_id</code>. Condition needed to unlock this condition.
     */
    public Integer getQuestsConditionsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>kalaazu.quests_conditions.quests_id</code>.
     */
    public void setQuestsId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.quests_conditions.quests_id</code>.
     */
    public Short getQuestsId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>kalaazu.quests_conditions.type</code>. 0 = collect, 1 = destroy, 2 = travel, 3 = one of, 4 = in order, 5 = accomplish before, 6 = on map
     */
    public void setType(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.quests_conditions.type</code>. 0 = collect, 1 = destroy, 2 = travel, 3 = one of, 4 = in order, 5 = accomplish before, 6 = on map
     */
    public Byte getType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>kalaazu.quests_conditions.value</code>.
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.quests_conditions.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Short, Byte, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Short, Byte, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return QuestsConditions.QUESTS_CONDITIONS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return QuestsConditions.QUESTS_CONDITIONS.QUESTS_CONDITIONS_ID;
    }

    @Override
    public Field<Short> field3() {
        return QuestsConditions.QUESTS_CONDITIONS.QUESTS_ID;
    }

    @Override
    public Field<Byte> field4() {
        return QuestsConditions.QUESTS_CONDITIONS.TYPE;
    }

    @Override
    public Field<String> field5() {
        return QuestsConditions.QUESTS_CONDITIONS.VALUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getQuestsConditionsId();
    }

    @Override
    public Short component3() {
        return getQuestsId();
    }

    @Override
    public Byte component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getValue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getQuestsConditionsId();
    }

    @Override
    public Short value3() {
        return getQuestsId();
    }

    @Override
    public Byte value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getValue();
    }

    @Override
    public QuestsConditionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public QuestsConditionsRecord value2(Integer value) {
        setQuestsConditionsId(value);
        return this;
    }

    @Override
    public QuestsConditionsRecord value3(Short value) {
        setQuestsId(value);
        return this;
    }

    @Override
    public QuestsConditionsRecord value4(Byte value) {
        setType(value);
        return this;
    }

    @Override
    public QuestsConditionsRecord value5(String value) {
        setValue(value);
        return this;
    }

    @Override
    public QuestsConditionsRecord values(Integer value1, Integer value2, Short value3, Byte value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestsConditionsRecord
     */
    public QuestsConditionsRecord() {
        super(QuestsConditions.QUESTS_CONDITIONS);
    }

    /**
     * Create a detached, initialised QuestsConditionsRecord
     */
    public QuestsConditionsRecord(Integer id, Integer questsConditionsId, Short questsId, Byte type, String value) {
        super(QuestsConditions.QUESTS_CONDITIONS);

        set(0, id);
        set(1, questsConditionsId);
        set(2, questsId);
        set(3, type);
        set(4, value);
    }
}
