/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.entities.tables.records;


import com.kalaazu.persistence.database.entities.tables.Users;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.sql.Timestamp;


/**
 * Contains the login information of the registered users.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record9<Integer, Timestamp, Short, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = 1199338010;

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(
            Integer id, Timestamp date, Short invitationCodesId, String name, String password, String email,
            String emailVerificationCode, Timestamp emailVerificationDate, String ip
    ) {
        super(Users.USERS);

        set(0, id);
        set(1, date);
        set(2, invitationCodesId);
        set(3, name);
        set(4, password);
        set(5, email);
        set(6, emailVerificationCode);
        set(7, emailVerificationDate);
        set(8, ip);
    }

    /**
     * Getter for <code>kalaazu.users.id</code>. Primary Key.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>kalaazu.users.id</code>. Primary Key.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>kalaazu.users.date</code>. Date when the user registered.
     */
    public Timestamp getDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>kalaazu.users.date</code>. Date when the user registered.
     */
    public void setDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>kalaazu.users.invitation_codes_id</code>. Invitation code used to register
     */
    public Short getInvitationCodesId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>kalaazu.users.invitation_codes_id</code>. Invitation code used to register
     */
    public void setInvitationCodesId(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>kalaazu.users.name</code>. User name.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kalaazu.users.name</code>. User name.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>kalaazu.users.password</code>. Password hash (argon).
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>kalaazu.users.password</code>. Password hash (argon).
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>kalaazu.users.email</code>. User email.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>kalaazu.users.email</code>. User email.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>kalaazu.users.email_verification_code</code>. Email verification code.
     */
    public String getEmailVerificationCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>kalaazu.users.email_verification_code</code>. Email verification code.
     */
    public void setEmailVerificationCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>kalaazu.users.email_verification_date</code>. Date when the user verified its email.
     */
    public Timestamp getEmailVerificationDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>kalaazu.users.email_verification_date</code>. Date when the user verified its email.
     */
    public void setEmailVerificationDate(Timestamp value) {
        set(7, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>kalaazu.users.ip</code>. Registration IP.
     */
    public String getIp() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>kalaazu.users.ip</code>. Registration IP.
     */
    public void setIp(String value) {
        set(8, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row9<Integer, Timestamp, Short, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Timestamp, Short, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<Timestamp> field2() {
        return Users.USERS.DATE;
    }

    @Override
    public Field<Short> field3() {
        return Users.USERS.INVITATION_CODES_ID;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.NAME;
    }

    @Override
    public Field<String> field5() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return Users.USERS.EMAIL;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.EMAIL_VERIFICATION_CODE;
    }

    @Override
    public Field<Timestamp> field8() {
        return Users.USERS.EMAIL_VERIFICATION_DATE;
    }

    @Override
    public Field<String> field9() {
        return Users.USERS.IP;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Timestamp component2() {
        return getDate();
    }

    @Override
    public Short component3() {
        return getInvitationCodesId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public String component7() {
        return getEmailVerificationCode();
    }

    @Override
    public Timestamp component8() {
        return getEmailVerificationDate();
    }

    @Override
    public String component9() {
        return getIp();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Timestamp value2() {
        return getDate();
    }

    @Override
    public Short value3() {
        return getInvitationCodesId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public String value7() {
        return getEmailVerificationCode();
    }

    @Override
    public Timestamp value8() {
        return getEmailVerificationDate();
    }

    @Override
    public String value9() {
        return getIp();
    }

    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(Timestamp value) {
        setDate(value);
        return this;
    }

    @Override
    public UsersRecord value3(Short value) {
        setInvitationCodesId(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public UsersRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setEmailVerificationCode(value);
        return this;
    }

    @Override
    public UsersRecord value8(Timestamp value) {
        setEmailVerificationDate(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public UsersRecord value9(String value) {
        setIp(value);
        return this;
    }

    @Override
    public UsersRecord values(
            Integer value1, Timestamp value2, Short value3, String value4, String value5, String value6, String value7,
            Timestamp value8, String value9
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
