/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database.tables;


import com.kalaazu.persistence.database.Indexes;
import com.kalaazu.persistence.database.Kalaazu;
import com.kalaazu.persistence.database.Keys;
import com.kalaazu.persistence.database.records.GalaxygatesProbabilitiesRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * Spin probabilities for the galaxy gates.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GalaxygatesProbabilities extends TableImpl<GalaxygatesProbabilitiesRecord> {

    /**
     * The reference instance of <code>kalaazu.galaxygates_probabilities</code>
     */
    public static final GalaxygatesProbabilities GALAXYGATES_PROBABILITIES = new GalaxygatesProbabilities();
    private static final long serialVersionUID = -1333122042;
    /**
     * The column <code>kalaazu.galaxygates_probabilities.id</code>. Primary Key.
     */
    public final TableField<GalaxygatesProbabilitiesRecord, Byte> ID = createField(
            DSL.name("id"),
            org.jooq.impl.SQLDataType.TINYINT.nullable(false).identity(true),
            this,
            "Primary Key."
    );
    /**
     * The column <code>kalaazu.galaxygates_probabilities.galaxygates_id</code>. The galaxy gate.
     */
    public final TableField<GalaxygatesProbabilitiesRecord, Byte> GALAXYGATES_ID = createField(
            DSL.name("galaxygates_id"),
            org.jooq.impl.SQLDataType.TINYINT.nullable(false),
            this,
            "The galaxy gate."
    );
    /**
     * The column <code>kalaazu.galaxygates_probabilities.type</code>. 0 = ammo, 1 = resource, 2 = voucher, 3 = logfile, 4 = part, 5 = special.
     */
    public final TableField<GalaxygatesProbabilitiesRecord, Byte> TYPE = createField(
            DSL.name("type"),
            org.jooq.impl.SQLDataType.TINYINT.nullable(false)
                                             .defaultValue(org.jooq.impl.DSL.field(
                                                     "0",
                                                     org.jooq.impl.SQLDataType.TINYINT
                                             )),
            this,
            "0 = ammo, 1 = resource, 2 = voucher, 3 = logfile, 4 = part, 5 = special."
    );
    /**
     * The column <code>kalaazu.galaxygates_probabilities.probability</code>. Probability of awarding one spin of this type.
     */
    public final TableField<GalaxygatesProbabilitiesRecord, Double> PROBABILITY = createField(
            DSL.name("probability"),
            org.jooq.impl.SQLDataType.FLOAT.nullable(false)
                                           .defaultValue(org.jooq.impl.DSL.field(
                                                   "100",
                                                   org.jooq.impl.SQLDataType.FLOAT
                                           )),
            this,
            "Probability of awarding one spin of this type."
    );

    /**
     * Create a <code>kalaazu.galaxygates_probabilities</code> table reference
     */
    public GalaxygatesProbabilities() {
        this(DSL.name("galaxygates_probabilities"), null);
    }

    /**
     * Create an aliased <code>kalaazu.galaxygates_probabilities</code> table reference
     */
    public GalaxygatesProbabilities(String alias) {
        this(DSL.name(alias), GALAXYGATES_PROBABILITIES);
    }

    /**
     * Create an aliased <code>kalaazu.galaxygates_probabilities</code> table reference
     */
    public GalaxygatesProbabilities(Name alias) {
        this(alias, GALAXYGATES_PROBABILITIES);
    }

    private GalaxygatesProbabilities(Name alias, Table<GalaxygatesProbabilitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GalaxygatesProbabilities(Name alias, Table<GalaxygatesProbabilitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Spin probabilities for the galaxy gates."));
    }

    public <O extends Record> GalaxygatesProbabilities(
            Table<O> child, ForeignKey<O, GalaxygatesProbabilitiesRecord> key
    ) {
        super(child, key, GALAXYGATES_PROBABILITIES);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GalaxygatesProbabilitiesRecord> getRecordType() {
        return GalaxygatesProbabilitiesRecord.class;
    }

    @Override
    public Schema getSchema() {
        return Kalaazu.KALAAZU;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(
                Indexes.GALAXYGATES_PROBABILITIES_GALAXYGATES_PROBABILITIES_GALAXYGATES,
                Indexes.GALAXYGATES_PROBABILITIES_PRIMARY
        );
    }

    @Override
    public Identity<GalaxygatesProbabilitiesRecord, Byte> getIdentity() {
        return Keys.IDENTITY_GALAXYGATES_PROBABILITIES;
    }

    @Override
    public UniqueKey<GalaxygatesProbabilitiesRecord> getPrimaryKey() {
        return Keys.KEY_GALAXYGATES_PROBABILITIES_PRIMARY;
    }

    @Override
    public List<UniqueKey<GalaxygatesProbabilitiesRecord>> getKeys() {
        return Arrays.<UniqueKey<GalaxygatesProbabilitiesRecord>>asList(Keys.KEY_GALAXYGATES_PROBABILITIES_PRIMARY);
    }

    @Override
    public List<ForeignKey<GalaxygatesProbabilitiesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GalaxygatesProbabilitiesRecord, ?>>asList(Keys.GALAXYGATES_PROBABILITIES_GALAXYGATES);
    }

    public Galaxygates galaxygates() {
        return new Galaxygates(this, Keys.GALAXYGATES_PROBABILITIES_GALAXYGATES);
    }

    @Override
    public GalaxygatesProbabilities as(String alias) {
        return new GalaxygatesProbabilities(DSL.name(alias), this);
    }

    @Override
    public GalaxygatesProbabilities as(Name alias) {
        return new GalaxygatesProbabilities(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GalaxygatesProbabilities rename(String name) {
        return new GalaxygatesProbabilities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GalaxygatesProbabilities rename(Name name) {
        return new GalaxygatesProbabilities(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Byte, Byte, Byte, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
