package package_73 {

public class class_196 {

    public static const CREATE_SETTINGS_WINDOW: String = "CREATE_SETTINGS_WINDOW";

    public static const SETTINGS_WINDOW_FUI_SAVE_SETTINGS: String = "SETTINGS_WINDOW_FUI_SAVE_SETTINGS";

    public static const SETTINGS_WINDOW_FUI_CANCEL_SETTINGS: String = "SETTINGS_WINDOW_FUI_CANCEL_SETTINGS";

    public static const SETTINGS_WINDOW_FUI_SETTING_CHANGED: String = "SETTINGS_WINDOW_FUI_SETTING_CHANGED";

    public static const SETTINGS_WINDOW_FUI_SAVE_SETTINGS_USER_REQUEST: String = "SETTINGS_WINDOW_FUI_SAVE_SETTINGS_USER_REQUEST";

    public static const SETTINGS_WINDOW_FUI_MODEL_CHANGED: String = "SETTINGS_WINDOW_FUI_MODEL_CHANGED";

    public static const SETTINGS_WINDOW_FUI_APPLY_MODEL_CHANGES: String = "SETTINGS_WINDOW_FUI_APPLY_MODEL_CHANGES";

    public static const SETTINGS_WINDOW_FUI_APPLY_SETTINGS_FROM_SERVER: String = "SETTINGS_WINDOW_FUI_APPLY_SETTINGS_FROM_SERVER";

    public static const SETTINGS_WINDOW_FUI_ENABLE_SAVE_BUTTON: String = "SETTINGS_WINDOW_FUI_ENABLE_SAVE_BUTTON";


    public function class_196() {
        super();
    }
}
}
