/*
 * This file is generated by jOOQ.
 */
package com.kalaazu.persistence.database;


import com.kalaazu.persistence.database.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Kalaazu extends SchemaImpl {

    /**
     * The reference instance of <code>kalaazu</code>
     */
    public static final  Kalaazu  KALAAZU          = new Kalaazu();
    private static final long     serialVersionUID = -248981595;
    /**
     * In game accounts.
     */
    public final         Accounts ACCOUNTS         = Accounts.ACCOUNTS;

    /**
     * Account's internal bank.
     */
    public final AccountsBanks ACCOUNTS_BANKS = AccountsBanks.ACCOUNTS_BANKS;

    /**
     * Logs from account's bank
     */
    public final AccountsBanksLogs ACCOUNTS_BANKS_LOGS = AccountsBanksLogs.ACCOUNTS_BANKS_LOGS;

    /**
     * Many to many relation table.
     */
    public final AccountsClansRoles ACCOUNTS_CLANS_ROLES = AccountsClansRoles.ACCOUNTS_CLANS_ROLES;

    /**
     * Configurations of the accounts.
     */
    public final AccountsConfigurations ACCOUNTS_CONFIGURATIONS = AccountsConfigurations.ACCOUNTS_CONFIGURATIONS;

    /**
     * Items of the configuration.
     */
    public final AccountsConfigurationsAccountsItems ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS = AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS;

    /**
     * Account's destroy history.
     */
    public final AccountsDestroys ACCOUNTS_DESTROYS = AccountsDestroys.ACCOUNTS_DESTROYS;

    /**
     * Account's drones.
     */
    public final AccountsDrones ACCOUNTS_DRONES = AccountsDrones.ACCOUNTS_DRONES;

    /**
     * Account's build galaxygates.
     */
    public final AccountsGalaxygates ACCOUNTS_GALAXYGATES = AccountsGalaxygates.ACCOUNTS_GALAXYGATES;

    /**
     * Hangars bough by an account.
     */
    public final AccountsHangars ACCOUNTS_HANGARS = AccountsHangars.ACCOUNTS_HANGARS;

    /**
     * Account's history events.
     */
    public final AccountsHistory ACCOUNTS_HISTORY = AccountsHistory.ACCOUNTS_HISTORY;

    /**
     * Items bough by an account.
     */
    public final AccountsItems ACCOUNTS_ITEMS = AccountsItems.ACCOUNTS_ITEMS;

    /**
     * Messaging system.
     */
    public final AccountsMessages ACCOUNTS_MESSAGES = AccountsMessages.ACCOUNTS_MESSAGES;

    /**
     * Account's PETs.
     */
    public final AccountsPets ACCOUNTS_PETS = AccountsPets.ACCOUNTS_PETS;

    /**
     * Quest status of the account.
     */
    public final AccountsQuests ACCOUNTS_QUESTS = AccountsQuests.ACCOUNTS_QUESTS;

    /**
     * Account ranking.
     */
    public final AccountsRankings ACCOUNTS_RANKINGS = AccountsRankings.ACCOUNTS_RANKINGS;

    /**
     * Ships bough by an account.
     */
    public final AccountsShips ACCOUNTS_SHIPS = AccountsShips.ACCOUNTS_SHIPS;

    /**
     * Skilltree for the account.
     */
    public final AccountsSkills ACCOUNTS_SKILLS = AccountsSkills.ACCOUNTS_SKILLS;

    /**
     * Skylab for the accounts.
     */
    public final AccountsSkylabs ACCOUNTS_SKYLABS = AccountsSkylabs.ACCOUNTS_SKYLABS;

    /**
     * Nanotech factory items.
     */
    public final AccountsTechfactories ACCOUNTS_TECHFACTORIES = AccountsTechfactories.ACCOUNTS_TECHFACTORIES;

    /**
     * Techfactory items from account.
     */
    public final AccountsTechfactoryItems ACCOUNTS_TECHFACTORY_ITEMS = AccountsTechfactoryItems.ACCOUNTS_TECHFACTORY_ITEMS;

    /**
     * Server clans.
     */
    public final Clans CLANS = Clans.CLANS;

    /**
     * Account applications to a clan.
     */
    public final ClansApplications CLANS_APPLICATIONS = ClansApplications.CLANS_APPLICATIONS;

    /**
     * Clan's internal bank.
     */
    public final ClansBanks CLANS_BANKS = ClansBanks.CLANS_BANKS;

    /**
     * Logs from clan's bank.
     */
    public final ClansBanksLogs CLANS_BANKS_LOGS = ClansBanksLogs.CLANS_BANKS_LOGS;

    /**
     * Clan CBS.
     */
    public final ClansBattlestations CLANS_BATTLESTATIONS = ClansBattlestations.CLANS_BATTLESTATIONS;

    /**
     * Items equipped in the CBS.
     */
    public final ClansBattlestationsItems CLANS_BATTLESTATIONS_ITEMS = ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS;

    /**
     * Logs from clan's battlestations.
     */
    public final ClansBattlestationsLogs CLANS_BATTLESTATIONS_LOGS = ClansBattlestationsLogs.CLANS_BATTLESTATIONS_LOGS;

    /**
     * Diplomacy table for clans.
     */
    public final ClansDiplomacies CLANS_DIPLOMACIES = ClansDiplomacies.CLANS_DIPLOMACIES;

    /**
     * Messages in the clan.
     */
    public final ClansMessages CLANS_MESSAGES = ClansMessages.CLANS_MESSAGES;

    /**
     * News of the clan.
     */
    public final ClansNews CLANS_NEWS = ClansNews.CLANS_NEWS;

    /**
     * Clan ranking.
     */
    public final ClansRanking CLANS_RANKING = ClansRanking.CLANS_RANKING;

    /**
     * Clan's roles.
     */
    public final ClansRoles CLANS_ROLES = ClansRoles.CLANS_ROLES;

    /**
     * Clan roles' permissions
     */
    public final ClansRolesPermissions CLANS_ROLES_PERMISSIONS = ClansRolesPermissions.CLANS_ROLES_PERMISSIONS;

    /**
     * Map collectables.
     */
    public final Collectables COLLECTABLES = Collectables.COLLECTABLES;

    /**
     * Contains server's events.
     */
    public final Events EVENTS = Events.EVENTS;

    /**
     * Contains server's factions.
     */
    public final Factions FACTIONS = Factions.FACTIONS;

    /**
     * Galaxy gates from the server.
     */
    public final Galaxygates GALAXYGATES = Galaxygates.GALAXYGATES;

    /**
     * Many to many relations for galaxygates and galaxygates_spins.
     */
    public final GalaxygatesGgSpins GALAXYGATES_GG_SPINS = GalaxygatesGgSpins.GALAXYGATES_GG_SPINS;

    /**
     * Many to many relations for galaxygates and galaxygates_waves.
     */
    public final GalaxygatesGgWaves GALAXYGATES_GG_WAVES = GalaxygatesGgWaves.GALAXYGATES_GG_WAVES;

    /**
     * Spin probabilities for the galaxy gates.
     */
    public final GalaxygatesProbabilities GALAXYGATES_PROBABILITIES = GalaxygatesProbabilities.GALAXYGATES_PROBABILITIES;

    /**
     * Stage spawn for each stage.
     */
    public final GalaxygatesSpawns GALAXYGATES_SPAWNS = GalaxygatesSpawns.GALAXYGATES_SPAWNS;

    /**
     * Spins from the galaxy gate.
     */
    public final GalaxygatesSpins GALAXYGATES_SPINS = GalaxygatesSpins.GALAXYGATES_SPINS;

    /**
     * Spawn stage for each wave.
     */
    public final GalaxygatesStages GALAXYGATES_STAGES = GalaxygatesStages.GALAXYGATES_STAGES;

    /**
     * Many to many relations for galaxygates_stages and galaxygates_spawns.
     */
    public final GalaxygatesStagesSpawns GALAXYGATES_STAGES_SPAWNS = GalaxygatesStagesSpawns.GALAXYGATES_STAGES_SPAWNS;

    /**
     * Waves of the galaxy gate.
     */
    public final GalaxygatesWaves GALAXYGATES_WAVES = GalaxygatesWaves.GALAXYGATES_WAVES;

    /**
     * Contains the invitation codes that can be used for registering.
     */
    public final InvitationCodes INVITATION_CODES = InvitationCodes.INVITATION_CODES;

    /**
     * Contains the redeem logs for the invitation codes.
     */
    public final InvitationCodesRedeemLogs INVITATION_CODES_REDEEM_LOGS = InvitationCodesRedeemLogs.INVITATION_CODES_REDEEM_LOGS;

    /**
     * Contains server's items.
     */
    public final Items ITEMS = Items.ITEMS;

    /**
     * Contains simple Key -&gt; Value entries.
     */
    public final KeyValue KEY_VALUE = KeyValue.KEY_VALUE;

    /**
     * Contains server's levels.
     */
    public final Levels LEVELS = Levels.LEVELS;

    /**
     * Contains the upgrade costs for each level.
     */
    public final LevelsUpgrades LEVELS_UPGRADES = LevelsUpgrades.LEVELS_UPGRADES;

    /**
     * In game maps.
     */
    public final Maps MAPS = Maps.MAPS;

    /**
     * Many to many relation table.
     */
    public final MapsNpcs MAPS_NPCS = MapsNpcs.MAPS_NPCS;

    /**
     * Portals on map.
     */
    public final MapsPortals MAPS_PORTALS = MapsPortals.MAPS_PORTALS;

    /**
     * Stations on map.
     */
    public final MapsStations MAPS_STATIONS = MapsStations.MAPS_STATIONS;

    /**
     * Server moderators.
     */
    public final Moderators MODERATORS = Moderators.MODERATORS;

    /**
     * Logged events made by moderators.
     */
    public final ModeratorsLogs MODERATORS_LOGS = ModeratorsLogs.MODERATORS_LOGS;

    /**
     * Moderator's roles.
     */
    public final ModeratorsRoles MODERATORS_ROLES = ModeratorsRoles.MODERATORS_ROLES;

    /**
     * Moderator roles' permissions
     */
    public final ModeratorsRolesPermissions MODERATORS_ROLES_PERMISSIONS = ModeratorsRolesPermissions.MODERATORS_ROLES_PERMISSIONS;

    /**
     * Server news.
     */
    public final News NEWS = News.NEWS;

    /**
     * Server NPCS.
     */
    public final Npcs NPCS = Npcs.NPCS;

    /**
     * Server permissions.
     */
    public final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * In game quests.
     */
    public final Quests QUESTS = Quests.QUESTS;

    /**
     * Quest's conditions.
     */
    public final QuestsConditions QUESTS_CONDITIONS = QuestsConditions.QUESTS_CONDITIONS;

    /**
     * Contains the rank system.
     */
    public final Ranks RANKS = Ranks.RANKS;

    /**
     * All rewards available so there's no need of JSON.
     */
    public final Rewards REWARDS = Rewards.REWARDS;

    /**
     * Many to many relations.
     */
    public final RewardsCollectables REWARDS_COLLECTABLES = RewardsCollectables.REWARDS_COLLECTABLES;

    /**
     * Many to many relations.
     */
    public final RewardsGalaxygates REWARDS_GALAXYGATES = RewardsGalaxygates.REWARDS_GALAXYGATES;

    /**
     * Many to many relations.
     */
    public final RewardsNpcs REWARDS_NPCS = RewardsNpcs.REWARDS_NPCS;

    /**
     * Many to many relations.
     */
    public final RewardsQuests REWARDS_QUESTS = RewardsQuests.REWARDS_QUESTS;

    /**
     * Many to many relations.
     */
    public final RewardsShips REWARDS_SHIPS = RewardsShips.REWARDS_SHIPS;

    /**
     * Many to many relations.
     */
    public final RewardsVouchers REWARDS_VOUCHERS = RewardsVouchers.REWARDS_VOUCHERS;

    /**
     * Server fired events.
     */
    public final ServerLogs SERVER_LOGS = ServerLogs.SERVER_LOGS;

    /**
     * Ships table.
     */
    public final Ships SHIPS = Ships.SHIPS;

    /**
     * Levels a skill can reach.
     */
    public final SkilltreeLevels SKILLTREE_LEVELS = SkilltreeLevels.SKILLTREE_LEVELS;

    /**
     * The available skills.
     */
    public final SkilltreeSkills SKILLTREE_SKILLS = SkilltreeSkills.SKILLTREE_SKILLS;

    /**
     * Requisites needed to unlock a skill upgrade.
     */
    public final SkilltreeUnlocks SKILLTREE_UNLOCKS = SkilltreeUnlocks.SKILLTREE_UNLOCKS;

    /**
     * Different skylab modules.
     */
    public final SkylabModules SKYLAB_MODULES = SkylabModules.SKYLAB_MODULES;

    /**
     * Item production costs.
     */
    public final TechfactoryCosts TECHFACTORY_COSTS = TechfactoryCosts.TECHFACTORY_COSTS;

    /**
     * Drones that can be build in the tech factory.
     */
    public final TechfactoryDrones TECHFACTORY_DRONES = TechfactoryDrones.TECHFACTORY_DRONES;

    /**
     * Items that can be build in the tech factory.
     */
    public final TechfactoryItems TECHFACTORY_ITEMS = TechfactoryItems.TECHFACTORY_ITEMS;

    /**
     * Trade items.
     */
    public final TradeItems TRADE_ITEMS = TradeItems.TRADE_ITEMS;

    /**
     * Contains the login information of the registered users.
     */
    public final Users USERS = Users.USERS;

    /**
     * Voucher codes.
     */
    public final Vouchers VOUCHERS = Vouchers.VOUCHERS;

    /**
     * Contains the redeem logs for the voucher codes.
     */
    public final VouchersRedeemLogs VOUCHERS_REDEEM_LOGS = VouchersRedeemLogs.VOUCHERS_REDEEM_LOGS;

    /**
     * No further instances allowed
     */
    private Kalaazu() {
        super("kalaazu", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Accounts.ACCOUNTS,
                AccountsBanks.ACCOUNTS_BANKS,
                AccountsBanksLogs.ACCOUNTS_BANKS_LOGS,
                AccountsClansRoles.ACCOUNTS_CLANS_ROLES,
                AccountsConfigurations.ACCOUNTS_CONFIGURATIONS,
                AccountsConfigurationsAccountsItems.ACCOUNTS_CONFIGURATIONS_ACCOUNTS_ITEMS,
                AccountsDestroys.ACCOUNTS_DESTROYS,
                AccountsDrones.ACCOUNTS_DRONES,
                AccountsGalaxygates.ACCOUNTS_GALAXYGATES,
                AccountsHangars.ACCOUNTS_HANGARS,
                AccountsHistory.ACCOUNTS_HISTORY,
                AccountsItems.ACCOUNTS_ITEMS,
                AccountsMessages.ACCOUNTS_MESSAGES,
                AccountsPets.ACCOUNTS_PETS,
                AccountsQuests.ACCOUNTS_QUESTS,
                AccountsRankings.ACCOUNTS_RANKINGS,
                AccountsShips.ACCOUNTS_SHIPS,
                AccountsSkills.ACCOUNTS_SKILLS,
                AccountsSkylabs.ACCOUNTS_SKYLABS,
                AccountsTechfactories.ACCOUNTS_TECHFACTORIES,
                AccountsTechfactoryItems.ACCOUNTS_TECHFACTORY_ITEMS,
                Clans.CLANS,
                ClansApplications.CLANS_APPLICATIONS,
                ClansBanks.CLANS_BANKS,
                ClansBanksLogs.CLANS_BANKS_LOGS,
                ClansBattlestations.CLANS_BATTLESTATIONS,
                ClansBattlestationsItems.CLANS_BATTLESTATIONS_ITEMS,
                ClansBattlestationsLogs.CLANS_BATTLESTATIONS_LOGS,
                ClansDiplomacies.CLANS_DIPLOMACIES,
                ClansMessages.CLANS_MESSAGES,
                ClansNews.CLANS_NEWS,
                ClansRanking.CLANS_RANKING,
                ClansRoles.CLANS_ROLES,
                ClansRolesPermissions.CLANS_ROLES_PERMISSIONS,
                Collectables.COLLECTABLES,
                Events.EVENTS,
                Factions.FACTIONS,
                Galaxygates.GALAXYGATES,
                GalaxygatesGgSpins.GALAXYGATES_GG_SPINS,
                GalaxygatesGgWaves.GALAXYGATES_GG_WAVES,
                GalaxygatesProbabilities.GALAXYGATES_PROBABILITIES,
                GalaxygatesSpawns.GALAXYGATES_SPAWNS,
                GalaxygatesSpins.GALAXYGATES_SPINS,
                GalaxygatesStages.GALAXYGATES_STAGES,
                GalaxygatesStagesSpawns.GALAXYGATES_STAGES_SPAWNS,
                GalaxygatesWaves.GALAXYGATES_WAVES,
                InvitationCodes.INVITATION_CODES,
                InvitationCodesRedeemLogs.INVITATION_CODES_REDEEM_LOGS,
                Items.ITEMS,
                KeyValue.KEY_VALUE,
                Levels.LEVELS,
                LevelsUpgrades.LEVELS_UPGRADES,
                Maps.MAPS,
                MapsNpcs.MAPS_NPCS,
                MapsPortals.MAPS_PORTALS,
                MapsStations.MAPS_STATIONS,
                Moderators.MODERATORS,
                ModeratorsLogs.MODERATORS_LOGS,
                ModeratorsRoles.MODERATORS_ROLES,
                ModeratorsRolesPermissions.MODERATORS_ROLES_PERMISSIONS,
                News.NEWS,
                Npcs.NPCS,
                Permissions.PERMISSIONS,
                Quests.QUESTS,
                QuestsConditions.QUESTS_CONDITIONS,
                Ranks.RANKS,
                Rewards.REWARDS,
                RewardsCollectables.REWARDS_COLLECTABLES,
                RewardsGalaxygates.REWARDS_GALAXYGATES,
                RewardsNpcs.REWARDS_NPCS,
                RewardsQuests.REWARDS_QUESTS,
                RewardsShips.REWARDS_SHIPS,
                RewardsVouchers.REWARDS_VOUCHERS,
                ServerLogs.SERVER_LOGS,
                Ships.SHIPS,
                SkilltreeLevels.SKILLTREE_LEVELS,
                SkilltreeSkills.SKILLTREE_SKILLS,
                SkilltreeUnlocks.SKILLTREE_UNLOCKS,
                SkylabModules.SKYLAB_MODULES,
                TechfactoryCosts.TECHFACTORY_COSTS,
                TechfactoryDrones.TECHFACTORY_DRONES,
                TechfactoryItems.TECHFACTORY_ITEMS,
                TradeItems.TRADE_ITEMS,
                Users.USERS,
                Vouchers.VOUCHERS,
                VouchersRedeemLogs.VOUCHERS_REDEEM_LOGS
        );
    }
}
